<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ES-es" xml:lang="ES-es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maestría en Ecología y Biodiversidad · Universidad del Magdalena">

<title>Guía de Práctica · Estimación e Inferencia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/clipboard/clipboard.min.js"></script>
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/popper.min.js"></script>
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/anchor.min.js"></script>
<link href="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Guia_Practica_Ejercicios_Refuerzo_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Guia_Practica_Ejercicios_Refuerzo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Guia_Practica_Ejercicios_Refuerzo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Guia_Practica_Ejercicios_Refuerzo_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner {
        background: #2098D9;
      }
</style>


</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Guía de Práctica · Estimación e Inferencia</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar todo el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Ocultar todo el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código fuente</a></li></ul></div></div>
            <p class="subtitle lead">Bioestadística y Diseño Experimental · Semana 1 · 2026-II — Material de refuerzo del Taller 2</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Maestría en Ecología y Biodiversidad · Universidad del Magdalena </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">27 de septiembre de 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#cómo-usar-esta-guía" id="toc-cómo-usar-esta-guía" class="nav-link active" data-scroll-target="#cómo-usar-esta-guía">Cómo usar esta guía</a></li>
  <li><a href="#parte-a-elección-e-implementación-de-la-prueba-correcta" id="toc-parte-a-elección-e-implementación-de-la-prueba-correcta" class="nav-link" data-scroll-target="#parte-a-elección-e-implementación-de-la-prueba-correcta">Parte A — Elección e implementación de la prueba correcta</a>
  <ul class="collapse">
  <li><a href="#sec-a1t2" id="toc-sec-a1t2" class="nav-link" data-scroll-target="#sec-a1t2">A1 — Talla de pargo y conectividad del manglar</a></li>
  <li><a href="#sec-a2t2" id="toc-sec-a2t2" class="nav-link" data-scroll-target="#sec-a2t2">A2 — Densidad de erizos antes y después de una mortalidad masiva</a></li>
  <li><a href="#sec-a3t2" id="toc-sec-a3t2" class="nav-link" data-scroll-target="#sec-a3t2">A3 — Clorofila-a en cuatro estaciones de una bahía</a></li>
  <li><a href="#sec-a4t2" id="toc-sec-a4t2" class="nav-link" data-scroll-target="#sec-a4t2">A4 — Planeando un estudio: dragado y cobertura de pastos marinos</a></li>
  </ul></li>
  <li><a href="#parte-b-identificación-del-error-diagnóstico-de-errores-de-inferencia" id="toc-parte-b-identificación-del-error-diagnóstico-de-errores-de-inferencia" class="nav-link" data-scroll-target="#parte-b-identificación-del-error-diagnóstico-de-errores-de-inferencia">Parte B — Identificación del error: diagnóstico de errores de inferencia</a>
  <ul class="collapse">
  <li><a href="#sec-b1t2" id="toc-sec-b1t2" class="nav-link" data-scroll-target="#sec-b1t2">B1 — Tiempo de manipuleo en tres zonas de pesca</a></li>
  <li><a href="#sec-b2t2" id="toc-sec-b2t2" class="nav-link" data-scroll-target="#sec-b2t2">B2 — “No significativo” interpretado como “no hay efecto”</a></li>
  <li><a href="#sec-b3t2" id="toc-sec-b3t2" class="nav-link" data-scroll-target="#sec-b3t2">B3 — Ignorar el pareo</a></li>
  <li><a href="#sec-b4t2" id="toc-sec-b4t2" class="nav-link" data-scroll-target="#sec-b4t2">B4 — Comparaciones múltiples sin corrección</a></li>
  </ul></li>
  <li><a href="#cierre" id="toc-cierre" class="nav-link" data-scroll-target="#cierre">Cierre</a>
  <ul class="collapse">
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div style="page-break-after: always;"></div>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="fig_portadas/guia_refuerzo/guia_portada.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:85.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<section id="cómo-usar-esta-guía" class="level2">
<h2 class="anchored" data-anchor-id="cómo-usar-esta-guía">Cómo usar esta guía</h2>
<p>Esta guía complementa el Taller 2 y su cuestionario de opción múltiple — no los reemplaza. Aquí el objetivo es distinto: en el Taller 1 se practicó cómo <strong>proponer un diseño</strong> y <strong>detectar fallas de diseño</strong>; en esta guía se hace lo mismo, pero del lado del <strong>análisis</strong>: elegir e implementar correctamente la prueba de inferencia, y reconocer los errores de interpretación que con más frecuencia arruinan un análisis por lo demás bien diseñado.</p>
<ul>
<li><strong>Parte A — Elección e implementación:</strong> 4 escenarios nuevos. De entrada no se indica si hace falta un t-test, un ANOVA, una prueba no paramétrica, o un cálculo de potencia.</li>
<li><strong>Parte B — Identificación del error:</strong> 4 viñetas de análisis ya “hechos”, cada una con un error de inferencia distinto — no de diseño (eso ya se trabajó en la guía del Taller 1), sino de cómo se interpretó o ejecutó el análisis.</li>
</ul>
<p>Cada ejercicio guarda su respuesta en un bloque colapsable — se recomienda intentar resolverlo antes de abrirlo.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># library(tidyverse)  # descomentar si se tiene instalado</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
<div style="page-break-after: always;"></div>
</section>
<section id="parte-a-elección-e-implementación-de-la-prueba-correcta" class="level1">
<h1>Parte A — Elección e implementación de la prueba correcta</h1>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="fig_portadas/guia_refuerzo/guia_parteA.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:75.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<section id="sec-a1t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-a1t2">A1 — Talla de pargo y conectividad del manglar</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo quiere saber si la talla de juveniles de pargo (<em>Lutjanus</em> spp.) difiere entre manglares con <strong>alta</strong> y <strong>baja</strong> conectividad a praderas de pastos marinos cercanas. Se midieron 15 juveniles en cada tipo de manglar.</p>
</div>
</div>
<ol type="1">
<li>¿Cuántos grupos hay, y qué tipo de prueba de la tabla de síntesis del taller se considera de entrada?</li>
<li>¿Qué se necesita revisar antes de confiar en el resultado?</li>
</ol>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>manglar <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">2</span>, <span class="dv">15</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Alta_conectividad"</span>, <span class="st">"Baja_conectividad"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>talla_pargo <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fu">c</span>(<span class="fl">18.5</span>, <span class="fl">14.8</span>)[<span class="fu">as.integer</span>(manglar)], <span class="at">sd =</span> <span class="fl">2.4</span>), <span class="dv">1</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>pargo_talla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(manglar, talla_pargo)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(talla_pargo <span class="sc">~</span> manglar, <span class="at">data =</span> pargo_talla, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Conectividad"</span>, <span class="at">ylab =</span> <span class="st">"Talla (cm)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Guia_Practica_Ejercicios_Refuerzo_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>2 grupos → t-test.</strong> Antes de correr cualquier análisis, se revisan las varianzas de cada grupo:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(pargo_talla<span class="sc">$</span>talla_pargo, pargo_talla<span class="sc">$</span>manglar, sd)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Alta_conectividad Baja_conectividad 
         2.456149          3.257884 </code></pre>
</div>
</div>
<p>Son razonablemente parecidas, pero no hace falta decidir “a mano” si se usa Welch — <code>t.test()</code> en R lo aplica por defecto:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(talla_pargo <span class="sc">~</span> manglar, <span class="at">data =</span> pargo_talla)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  talla_pargo by manglar
t = 5.3981, df = 26.029, p-value = 1.175e-05
alternative hypothesis: true difference in means between group Alta_conectividad and group Baja_conectividad is not equal to 0
95 percent confidence interval:
 3.521377 7.851956
sample estimates:
mean in group Alta_conectividad mean in group Baja_conectividad 
                       19.65333                        13.96667 </code></pre>
</div>
</div>
<p>El resultado es claramente significativo (p = 1.18e-05): los juveniles en manglares de alta conectividad son en promedio más grandes. Con solo 2 grupos, siempre se corre el mismo <code>t.test()</code> — la corrección de Welch va incluida, se revise o no la homocedasticidad primero.</p>
</div>
</div>
</div>
</section>
<section id="sec-a2t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-a2t2">A2 — Densidad de erizos antes y después de una mortalidad masiva</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tras un evento de mortalidad masiva (die-off) por una posible enfermedad, un equipo regresó a <strong>los mismos 10 sitios</strong> donde ya tenía datos de densidad de erizos (<em>Diadema antillarum</em>) previos al evento, y volvió a censar.</p>
</div>
</div>
<ol type="1">
<li>¿Las dos mediciones son de sitios independientes, o del mismo sitio dos veces?</li>
<li>¿Qué prueba corresponde?</li>
</ol>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n_sitios2 <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>densidad_antes <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_sitios2, <span class="at">mean =</span> <span class="dv">12</span>, <span class="at">sd =</span> <span class="dv">3</span>), <span class="dv">1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mortalidad <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_sitios2, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">2</span>), <span class="dv">1</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>densidad_despues <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">pmax</span>(<span class="dv">0</span>, densidad_antes <span class="sc">-</span> mortalidad), <span class="dv">1</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>erizos_dieoff <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sitio =</span> <span class="fu">paste0</span>(<span class="st">"S"</span>, <span class="dv">1</span><span class="sc">:</span>n_sitios2), densidad_antes, densidad_despues)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>erizos_dieoff</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   sitio densidad_antes densidad_despues
1     S1           13.6              7.4
2     S2            8.8              3.3
3     S3           12.4              5.8
4     S4           11.7              5.2
5     S5           10.0              8.1
6     S6            4.5              0.0
7     S7            9.8              1.6
8     S8            8.9              1.5
9     S9           12.3              6.9
10   S10           10.6              2.2</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Mismo sitio, medido dos veces → <strong>t-test pareado</strong>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(erizos_dieoff<span class="sc">$</span>densidad_antes, erizos_dieoff<span class="sc">$</span>densidad_despues, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  erizos_dieoff$densidad_antes and erizos_dieoff$densidad_despues
t = 10.031, df = 9, p-value = 3.486e-06
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 4.693437 7.426563
sample estimates:
mean difference 
           6.06 </code></pre>
</div>
</div>
<p>t = 10.03, p = 3.5e-06 — caída clara y consistente en la densidad tras el evento. En la Parte B de esta guía (B3) se verá qué tan distinto habría salido el resultado si se hubiera ignorado el pareo.</p>
</div>
</div>
</div>
</section>
<section id="sec-a3t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-a3t2">A3 — Clorofila-a en cuatro estaciones de una bahía</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo de monitoreo mide la concentración de clorofila-a (indicador de eutrofización) en <strong>4 estaciones</strong> de una bahía, con distinta influencia de escorrentía continental. Este tipo de variable ambiental suele tener una distribución muy asimétrica (muchos valores bajos, unos pocos muy altos).</p>
</div>
</div>
<ol type="1">
<li>¿Cuántos grupos hay, y qué prueba se consideraría de entrada?</li>
<li>Antes de confiar en esa prueba, ¿qué se tiene que revisar — y qué se haría si falla?</li>
</ol>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>estacion <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"E1_baja_escorrentia"</span>, <span class="st">"E2"</span>, <span class="st">"E3"</span>, <span class="st">"E4_alta_escorrentia"</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>lambda_chl <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">18</span>)[<span class="fu">as.integer</span>(estacion)]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>clorofila <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rgamma</span>(<span class="dv">36</span>, <span class="at">shape =</span> <span class="fl">0.8</span>, <span class="at">rate =</span> <span class="fl">0.8</span><span class="sc">/</span>lambda_chl), <span class="dv">2</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>bahia_chl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(estacion, clorofila)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Estación"</span>, <span class="at">ylab =</span> <span class="st">"Clorofila-a (µg/L)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Guia_Practica_Ejercicios_Refuerzo_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>4 grupos → candidato inicial: ANOVA.</strong> Pero primero se revisa:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mod_a3t2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(mod_a3t2))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(mod_a3t2)
W = 0.92498, p-value = 0.01768</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  clorofila by estacion
Bartlett's K-squared = 22.164, df = 3, p-value = 6.03e-05</code></pre>
</div>
</div>
<p>Ambos fallan — normalidad <strong>y</strong> homocedasticidad (algo muy típico en variables ambientales con distribución muy sesgada, como concentraciones o conteos). A diferencia del caso del Taller 2 (Parte 8, pargo y conectividad), donde solo fallaba la homocedasticidad, aquí falla también la normalidad — así que ni el ANOVA clásico ni el ANOVA de Welch son apropiados. La alternativa correcta es <strong>Kruskal-Wallis</strong>:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  clorofila by estacion
Kruskal-Wallis chi-squared = 17.777, df = 3, p-value = 0.000489</code></pre>
</div>
</div>
<p>p = 0.00049 — diferencias claras entre estaciones. Kruskal-Wallis no exige normalidad, pero sí es sensible a dispersiones muy distintas entre grupos (aquí la desviación estándar va de 0,9 en E1 a 7,7 en E3). Por eso se interpreta como “las distribuciones de clorofila difieren entre estaciones”, no estrictamente como diferencias de medianas. Para variables continuas, positivas y asimétricas como esta, la alternativa más completa es un <strong>GLM con distribución Gamma</strong>, que se verá en la Semana 2.</p>
</div>
</div>
</div>
</section>
<section id="sec-a4t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-a4t2">A4 — Planeando un estudio: dragado y cobertura de pastos marinos</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antes de salir a campo, un equipo quiere saber cuántas parcelas necesita por grupo para detectar una diferencia de <strong>8 puntos porcentuales</strong> de cobertura de pastos marinos entre zonas con y sin actividad de dragado reciente, con una potencia del 80%. Un estudio piloto previo, en un sistema similar, reportó una desviación estándar de 11 puntos porcentuales.</p>
</div>
</div>
<ol type="1">
<li>¿Qué función de R (de las usadas en la Parte 7 del taller) responde esta pregunta?</li>
<li>¿Qué le pasaría al <code>n</code> necesario si la variabilidad del sistema fuera mayor (sd = 15 en vez de 11)?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="dv">8</span>, <span class="at">sd =</span> <span class="dv">11</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 30.66918
          delta = 8
             sd = 11
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>n ≈ 31 parcelas por grupo. Se compara con una variabilidad mayor:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="dv">8</span>, <span class="at">sd =</span> <span class="dv">15</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 56.16413
          delta = 8
             sd = 15
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>Con sd = 15, el <code>n</code> necesario sube a ≈57 por grupo — más del doble. Cuanto más “ruidoso” es el sistema, más réplicas se necesitan para detectar la misma diferencia con la misma confianza. Por eso vale la pena usar la variabilidad de un piloto real (o de la literatura de la línea de investigación) en vez de inventar un número.</p>
</div>
</div>
</div>
<hr>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="parte-b-identificación-del-error-diagnóstico-de-errores-de-inferencia" class="level1">
<h1>Parte B — Identificación del error: diagnóstico de errores de inferencia</h1>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="fig_portadas/guia_refuerzo/guia_parteB.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:75.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p>Cada viñeta muestra un análisis ya “corrido”. Conviene identificar qué está mal antes de ver la respuesta.</p>
<section id="sec-b1t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-b1t2">B1 — Tiempo de manipuleo en tres zonas de pesca</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La viñeta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un investigador compara el tiempo de manipuleo de la captura entre pesca artesanal, semi-industrial e industrial (3 zonas). Sin revisar ningún supuesto, corrió directamente un ANOVA de una vía, obtuvo p = 0.0585, y concluyó que <strong>no hay diferencias</strong> entre tipos de pesca.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>zona_pesca <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">3</span>, <span class="dv">12</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Artesanal"</span>, <span class="st">"Semi_industrial"</span>, <span class="st">"Industrial"</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>lambda_b1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">7</span>)[<span class="fu">as.integer</span>(zona_pesca)]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>tiempo_manipuleo <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rexp</span>(<span class="dv">36</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span>lambda_b1), <span class="dv">1</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>manipuleo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(zona_pesca, tiempo_manipuleo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="1">
<li>¿Qué le faltó revisar antes de confiar en ese ANOVA?</li>
<li>¿Cambia la conclusión si se revisa?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Error: se saltó el diagnóstico de normalidad.</strong> El tiempo de manipuleo, como muchas variables de tiempo, tiene una distribución muy sesgada (no negativa, cola larga a la derecha) — exactamente el tipo de variable que rara vez es normal.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod_b1t2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(tiempo_manipuleo <span class="sc">~</span> zona_pesca, <span class="at">data =</span> manipuleo)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(mod_b1t2))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(mod_b1t2)
W = 0.78079, p-value = 6.918e-06</code></pre>
</div>
</div>
<p>W bajo, p = 6.9e-06 — normalidad claramente violada. Con eso en mente, la prueba correcta es Kruskal-Wallis, no el ANOVA que ya se corrió:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(tiempo_manipuleo <span class="sc">~</span> zona_pesca, <span class="at">data =</span> manipuleo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  tiempo_manipuleo by zona_pesca
Kruskal-Wallis chi-squared = 7.661, df = 2, p-value = 0.0217</code></pre>
</div>
</div>
<p><strong>La conclusión cambia:</strong> el ANOVA (mal aplicado) daba p = 0.0585, “no significativo” — pero Kruskal-Wallis, la prueba que sí respeta la falta de normalidad, da p = 0.0217, <strong>significativo</strong>. Al saltarse el diagnóstico, el investigador estuvo a punto de perderse un efecto real.</p>
</div>
</div>
</div>
</section>
<section id="sec-b2t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-b2t2">B2 — “No significativo” interpretado como “no hay efecto”</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La viñeta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo comparó un sitio control contra un sitio con impacto antrópico reciente, con solo <strong>6 réplicas por grupo</strong> (limitación de tiempo de campo). El t-test dio p = 0.25, y el equipo concluyó en su informe: <em>“no hay evidencia de que el impacto antrópico afecte la variable medida”</em>.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>n_chico <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>sitio_control <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_chico, <span class="at">mean =</span> <span class="dv">40</span>, <span class="at">sd =</span> <span class="dv">9</span>), <span class="dv">1</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>sitio_impacto <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_chico, <span class="at">mean =</span> <span class="dv">34</span>, <span class="at">sd =</span> <span class="dv">9</span>), <span class="dv">1</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="1">
<li>Con solo 6 réplicas por grupo, ¿qué tan probable es que el estudio detecte un efecto moderado aunque exista de verdad?</li>
<li>¿Es correcto decir que “no hay efecto”, o sería más preciso decir otra cosa?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Error: confundir “no se encontró evidencia significativa” con “se demostró que no hay efecto”.</strong> Un p-valor alto no prueba la hipótesis nula — solo dice que, con estos datos, no hubo evidencia suficiente para rechazarla.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sitio_control, sitio_impacto)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sitio_control and sitio_impacto
t = 1.2647, df = 6.2416, p-value = 0.2511
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -4.935147 15.701814
sample estimates:
mean of x mean of y 
 34.48333  29.10000 </code></pre>
</div>
</div>
<p>Con n = 6 por grupo, se calcula qué tan probable era detectar una diferencia real de esa magnitud:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n =</span> n_chico, <span class="at">delta =</span> <span class="dv">6</span>, <span class="at">sd =</span> <span class="dv">9</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 6
          delta = 6
             sd = 9
      sig.level = 0.05
          power = 0.1805033
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>Potencia ≈ 18%. Con esa potencia, aunque el impacto antrópico <strong>sí</strong> tuviera un efecto real de esa magnitud, el estudio tenía más de 4 de cada 5 probabilidades de <strong>no</strong> detectarlo. La conclusión correcta no es “no hay efecto” — es “este estudio, con este tamaño de muestra, no tuvo potencia suficiente para detectar un efecto de esta magnitud si existiera”. La diferencia es enorme para un informe técnico o un artículo.</p>
</div>
</div>
</div>
</section>
<section id="sec-b3t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-b3t2">B3 — Ignorar el pareo</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La viñeta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Retomando el diseño de A2 (mismos sitios, antes/después), un asistente de investigación analizó los datos con un t-test de dos muestras <strong>independientes</strong>, en vez de pareado, “porque son solo dos columnas de números”.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>n_par <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>antes_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_par, <span class="at">mean =</span> <span class="dv">25</span>, <span class="at">sd =</span> <span class="dv">6</span>), <span class="dv">1</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>cambio_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_par, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="fl">1.5</span>), <span class="dv">1</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>despues_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(antes_b3 <span class="sc">-</span> cambio_b3, <span class="dv">1</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="1">
<li>¿Qué información usa el t-test pareado que el independiente ignora por completo?</li>
<li>¿Qué se espera que le pase a la conclusión si se tratan datos pareados como independientes?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Error: tratar datos pareados (mismo sitio medido dos veces) como si fueran dos grupos independientes.</strong> El t-test independiente ignora que cada par de valores viene del mismo sitio — trata la variabilidad <em>entre sitios</em> como si fuera parte del “ruido” de la comparación, cuando en realidad no tiene nada que ver con el cambio antes/después.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Pareado (correcto):</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Pareado (correcto):</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(antes_b3, despues_b3, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  antes_b3 and despues_b3
t = 9.3657, df = 9, p-value = 6.157e-06
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 3.557188 5.822812
sample estimates:
mean difference 
           4.69 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Independiente (incorrecto):</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Independiente (incorrecto):</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(antes_b3, despues_b3, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  antes_b3 and despues_b3
t = 1.874, df = 17.622, p-value = 0.07761
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.5760885  9.9560885
sample estimates:
mean of x mean of y 
    21.52     16.83 </code></pre>
</div>
</div>
<p><strong>La conclusión cambia por completo:</strong> pareado da p = 6.2e-06 (altamente significativo); tratado como independiente da p = 0.078, <strong>no significativo</strong> al nivel usual de 0.05. Con los mismos datos, el error de no parear pudo haber llevado a reportar “no hay evidencia de cambio” cuando en realidad el cambio es muy claro — simplemente estaba oculto por la variabilidad entre sitios, que el pareo remueve.</p>
</div>
</div>
</div>
</section>
<section id="sec-b4t2" class="level2">
<h2 class="anchored" data-anchor-id="sec-b4t2">B4 — Comparaciones múltiples sin corrección</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La viñeta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un estudiante compara una variable entre 4 grupos experimentales. En vez de correr un solo ANOVA, decidió correr un <strong>t-test independiente para cada par posible de grupos</strong> (6 comparaciones en total), y reportó como “hallazgo” la única comparación que dio p &lt; 0.05.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>grupo_b4 <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">4</span>, <span class="dv">10</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>, <span class="st">"G4"</span>))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>valor_b4 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd =</span> <span class="dv">5</span>), <span class="dv">1</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>datos_b4 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(grupo_b4, valor_b4)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="1">
<li>Si se repite una prueba con α = 0.05 muchas veces, aunque no exista ningún efecto real, ¿qué probabilidad hay de que <strong>al menos una</strong> salga “significativa” solo por azar?</li>
<li>¿Qué debió haberse corrido en su lugar?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Verificación del razonamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Error: comparaciones múltiples sin corrección, inflando el error tipo I.</strong> Cada t-test individual tiene 5% de probabilidad de un falso positivo — pero con 6 comparaciones, la probabilidad de que <strong>al menos una</strong> salga significativa por puro azar es mucho mayor a 5%.</p>
<p>En esta simulación, <strong>no se programó ninguna diferencia real entre los 4 grupos</strong> (misma media, mismo sd). Aun así:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>niveles <span class="ot">&lt;-</span> <span class="fu">levels</span>(grupo_b4)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>pares <span class="ot">&lt;-</span> <span class="fu">combn</span>(niveles, <span class="dv">2</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>ps <span class="ot">&lt;-</span> <span class="fu">apply</span>(pares, <span class="dv">2</span>, <span class="cf">function</span>(p) {</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(valor_b4[grupo_b4 <span class="sc">==</span> p[<span class="dv">1</span>]], valor_b4[grupo_b4 <span class="sc">==</span> p[<span class="dv">2</span>]])<span class="sc">$</span>p.value</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ps) <span class="ot">&lt;-</span> <span class="fu">apply</span>(pares, <span class="dv">2</span>, paste, <span class="at">collapse =</span> <span class="st">" vs "</span>)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ps, <span class="dv">4</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>G1 vs G2 G1 vs G3 G1 vs G4 G2 vs G3 G2 vs G4 G3 vs G4 
  0.3996   0.0192   0.0848   0.1279   0.5253   0.2260 </code></pre>
</div>
</div>
<p>Una comparación (G1 vs G3) sale “significativa” (p = 0.019) — puro azar, disfrazado de hallazgo. El ANOVA de una vía, la prueba diseñada para comparar los 4 grupos a la vez con un solo error tipo I controlado, correctamente <strong>no</strong> detecta diferencias:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(valor_b4 <span class="sc">~</span> grupo_b4, <span class="at">data =</span> datos_b4))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
grupo_b4     3  174.3   58.11   2.624 0.0654 .
Residuals   36  797.3   22.15                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>La lección:</strong> cuando se quiere comparar más de 2 grupos, se corre primero un ANOVA (o Kruskal-Wallis), no una serie de t-tests de a pares. Si el ANOVA es significativo y se necesita saber cuáles pares difieren, existen comparaciones post-hoc (como <code>TukeyHSD()</code>, que se usa en la Parte 4 del Taller 2) diseñadas específicamente para controlar el error acumulado — correr t-tests sueltos no lo hace.</p>
</div>
</div>
</div>
</section>
</section>
<section id="cierre" class="level1">
<h1>Cierre</h1>
<p>Estos 8 ejercicios apuntan a la misma habilidad desde ángulos distintos: elegir la herramienta de inferencia correcta para cada pregunta, y reconocer cuándo un análisis —propio o ajeno— tiene un problema que ningún p-valor bonito puede tapar. Es exactamente el tipo de revisión que un jurado de tesis, o un revisor de artículo, le hará al propio trabajo — mejor practicarlo ahora, con datos simulados, que descubrirlo tarde con los datos propios.</p>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<p>Los escenarios de esta guía son de elaboración propia para este curso; no reproducen ejercicios ni datos de las fuentes citadas en el Taller 2.</p>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Guía de Práctica · Estimación e Inferencia"</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Bioestadística y Diseño Experimental · Semana 1 · 2026-II — Material de refuerzo del Taller 2"</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Maestría en Ecología y Biodiversidad · Universidad del Magdalena"</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner:</span><span class="co"> "#2098D9"</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true    # Tabla de contenido</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: Menú flotante</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true     # Opción para descargar los códigos</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true     # Visualización de los códigos en el reporte</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> ES-es</span></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.85\\linewidth"</span></span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"fig_portadas/guia_refuerzo/guia_portada.png"</span>)</span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-31"><a href="#cb46-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cómo usar esta guía</span></span>
<span id="cb46-32"><a href="#cb46-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-33"><a href="#cb46-33" aria-hidden="true" tabindex="-1"></a>Esta guía complementa el Taller 2 y su cuestionario de opción múltiple — no los reemplaza. Aquí el objetivo es distinto: en el Taller 1 se practicó cómo **proponer un diseño** y **detectar fallas de diseño**; en esta guía se hace lo mismo, pero del lado del **análisis**: elegir e implementar correctamente la prueba de inferencia, y reconocer los errores de interpretación que con más frecuencia arruinan un análisis por lo demás bien diseñado.</span>
<span id="cb46-34"><a href="#cb46-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-35"><a href="#cb46-35" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Parte A — Elección e implementación:** 4 escenarios nuevos. De entrada no se indica si hace falta un t-test, un ANOVA, una prueba no paramétrica, o un cálculo de potencia.</span>
<span id="cb46-36"><a href="#cb46-36" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Parte B — Identificación del error:** 4 viñetas de análisis ya "hechos", cada una con un error de inferencia distinto — no de diseño (eso ya se trabajó en la guía del Taller 1), sino de cómo se interpretó o ejecutó el análisis.</span>
<span id="cb46-37"><a href="#cb46-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-38"><a href="#cb46-38" aria-hidden="true" tabindex="-1"></a>Cada ejercicio guarda su respuesta en un bloque colapsable — se recomienda intentar resolverlo antes de abrirlo.</span>
<span id="cb46-39"><a href="#cb46-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-42"><a href="#cb46-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-43"><a href="#cb46-43" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb46-44"><a href="#cb46-44" aria-hidden="true" tabindex="-1"></a><span class="co"># library(tidyverse)  # descomentar si se tiene instalado</span></span>
<span id="cb46-45"><a href="#cb46-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-46"><a href="#cb46-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-47"><a href="#cb46-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-48"><a href="#cb46-48" aria-hidden="true" tabindex="-1"></a>---------------</span>
<span id="cb46-49"><a href="#cb46-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-50"><a href="#cb46-50" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb46-51"><a href="#cb46-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-52"><a href="#cb46-52" aria-hidden="true" tabindex="-1"></a><span class="fu"># Parte A — Elección e implementación de la prueba correcta</span></span>
<span id="cb46-53"><a href="#cb46-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-54"><a href="#cb46-54" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb46-55"><a href="#cb46-55" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.75\\linewidth"</span></span>
<span id="cb46-56"><a href="#cb46-56" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb46-57"><a href="#cb46-57" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb46-58"><a href="#cb46-58" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"fig_portadas/guia_refuerzo/guia_parteA.png"</span>)</span>
<span id="cb46-59"><a href="#cb46-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-60"><a href="#cb46-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-61"><a href="#cb46-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-62"><a href="#cb46-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## A1 — Talla de pargo y conectividad del manglar {#sec-a1t2}</span></span>
<span id="cb46-63"><a href="#cb46-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-64"><a href="#cb46-64" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-65"><a href="#cb46-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### El contexto</span></span>
<span id="cb46-66"><a href="#cb46-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-67"><a href="#cb46-67" aria-hidden="true" tabindex="-1"></a>Un equipo quiere saber si la talla de juveniles de pargo (*Lutjanus* spp.) difiere entre manglares con **alta** y **baja** conectividad a praderas de pastos marinos cercanas. Se midieron 15 juveniles en cada tipo de manglar.</span>
<span id="cb46-68"><a href="#cb46-68" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-69"><a href="#cb46-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-70"><a href="#cb46-70" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Cuántos grupos hay, y qué tipo de prueba de la tabla de síntesis del taller se considera de entrada?</span>
<span id="cb46-71"><a href="#cb46-71" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Qué se necesita revisar antes de confiar en el resultado?</span>
<span id="cb46-72"><a href="#cb46-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-75"><a href="#cb46-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-76"><a href="#cb46-76" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb46-77"><a href="#cb46-77" aria-hidden="true" tabindex="-1"></a>manglar <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">2</span>, <span class="dv">15</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Alta_conectividad"</span>, <span class="st">"Baja_conectividad"</span>))</span>
<span id="cb46-78"><a href="#cb46-78" aria-hidden="true" tabindex="-1"></a>talla_pargo <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fu">c</span>(<span class="fl">18.5</span>, <span class="fl">14.8</span>)[<span class="fu">as.integer</span>(manglar)], <span class="at">sd =</span> <span class="fl">2.4</span>), <span class="dv">1</span>)</span>
<span id="cb46-79"><a href="#cb46-79" aria-hidden="true" tabindex="-1"></a>pargo_talla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(manglar, talla_pargo)</span>
<span id="cb46-80"><a href="#cb46-80" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(talla_pargo <span class="sc">~</span> manglar, <span class="at">data =</span> pargo_talla, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb46-81"><a href="#cb46-81" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Conectividad"</span>, <span class="at">ylab =</span> <span class="st">"Talla (cm)"</span>)</span>
<span id="cb46-82"><a href="#cb46-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-83"><a href="#cb46-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-84"><a href="#cb46-84" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-85"><a href="#cb46-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-86"><a href="#cb46-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-87"><a href="#cb46-87" aria-hidden="true" tabindex="-1"></a>**2 grupos → t-test.** Antes de correr cualquier análisis, se revisan las varianzas de cada grupo:</span>
<span id="cb46-88"><a href="#cb46-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-91"><a href="#cb46-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-92"><a href="#cb46-92" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(pargo_talla<span class="sc">$</span>talla_pargo, pargo_talla<span class="sc">$</span>manglar, sd)</span>
<span id="cb46-93"><a href="#cb46-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-94"><a href="#cb46-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-95"><a href="#cb46-95" aria-hidden="true" tabindex="-1"></a>Son razonablemente parecidas, pero no hace falta decidir "a mano" si se usa Welch — <span class="in">`t.test()`</span> en R lo aplica por defecto:</span>
<span id="cb46-96"><a href="#cb46-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-99"><a href="#cb46-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-100"><a href="#cb46-100" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(talla_pargo <span class="sc">~</span> manglar, <span class="at">data =</span> pargo_talla)</span>
<span id="cb46-101"><a href="#cb46-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-102"><a href="#cb46-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-103"><a href="#cb46-103" aria-hidden="true" tabindex="-1"></a>El resultado es claramente significativo (p = 1.18e-05): los juveniles en manglares de alta conectividad son en promedio más grandes. Con solo 2 grupos, siempre se corre el mismo <span class="in">`t.test()`</span> — la corrección de Welch va incluida, se revise o no la homocedasticidad primero.</span>
<span id="cb46-104"><a href="#cb46-104" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-105"><a href="#cb46-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-106"><a href="#cb46-106" aria-hidden="true" tabindex="-1"></a><span class="fu">## A2 — Densidad de erizos antes y después de una mortalidad masiva {#sec-a2t2}</span></span>
<span id="cb46-107"><a href="#cb46-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-108"><a href="#cb46-108" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-109"><a href="#cb46-109" aria-hidden="true" tabindex="-1"></a><span class="fu">### El contexto</span></span>
<span id="cb46-110"><a href="#cb46-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-111"><a href="#cb46-111" aria-hidden="true" tabindex="-1"></a>Tras un evento de mortalidad masiva (die-off) por una posible enfermedad, un equipo regresó a **los mismos 10 sitios** donde ya tenía datos de densidad de erizos (*Diadema antillarum*) previos al evento, y volvió a censar.</span>
<span id="cb46-112"><a href="#cb46-112" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-113"><a href="#cb46-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-114"><a href="#cb46-114" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Las dos mediciones son de sitios independientes, o del mismo sitio dos veces?</span>
<span id="cb46-115"><a href="#cb46-115" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Qué prueba corresponde?</span>
<span id="cb46-116"><a href="#cb46-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-119"><a href="#cb46-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-120"><a href="#cb46-120" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb46-121"><a href="#cb46-121" aria-hidden="true" tabindex="-1"></a>n_sitios2 <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb46-122"><a href="#cb46-122" aria-hidden="true" tabindex="-1"></a>densidad_antes <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_sitios2, <span class="at">mean =</span> <span class="dv">12</span>, <span class="at">sd =</span> <span class="dv">3</span>), <span class="dv">1</span>)</span>
<span id="cb46-123"><a href="#cb46-123" aria-hidden="true" tabindex="-1"></a>mortalidad <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_sitios2, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">2</span>), <span class="dv">1</span>)</span>
<span id="cb46-124"><a href="#cb46-124" aria-hidden="true" tabindex="-1"></a>densidad_despues <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">pmax</span>(<span class="dv">0</span>, densidad_antes <span class="sc">-</span> mortalidad), <span class="dv">1</span>)</span>
<span id="cb46-125"><a href="#cb46-125" aria-hidden="true" tabindex="-1"></a>erizos_dieoff <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sitio =</span> <span class="fu">paste0</span>(<span class="st">"S"</span>, <span class="dv">1</span><span class="sc">:</span>n_sitios2), densidad_antes, densidad_despues)</span>
<span id="cb46-126"><a href="#cb46-126" aria-hidden="true" tabindex="-1"></a>erizos_dieoff</span>
<span id="cb46-127"><a href="#cb46-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-128"><a href="#cb46-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-129"><a href="#cb46-129" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-130"><a href="#cb46-130" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-131"><a href="#cb46-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-132"><a href="#cb46-132" aria-hidden="true" tabindex="-1"></a>Mismo sitio, medido dos veces → **t-test pareado**.</span>
<span id="cb46-133"><a href="#cb46-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-136"><a href="#cb46-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-137"><a href="#cb46-137" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(erizos_dieoff<span class="sc">$</span>densidad_antes, erizos_dieoff<span class="sc">$</span>densidad_despues, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-138"><a href="#cb46-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-139"><a href="#cb46-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-140"><a href="#cb46-140" aria-hidden="true" tabindex="-1"></a>t = 10.03, p = 3.5e-06 — caída clara y consistente en la densidad tras el evento. En la Parte B de esta guía (B3) se verá qué tan distinto habría salido el resultado si se hubiera ignorado el pareo.</span>
<span id="cb46-141"><a href="#cb46-141" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-142"><a href="#cb46-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-143"><a href="#cb46-143" aria-hidden="true" tabindex="-1"></a><span class="fu">## A3 — Clorofila-a en cuatro estaciones de una bahía {#sec-a3t2}</span></span>
<span id="cb46-144"><a href="#cb46-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-145"><a href="#cb46-145" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-146"><a href="#cb46-146" aria-hidden="true" tabindex="-1"></a><span class="fu">### El contexto</span></span>
<span id="cb46-147"><a href="#cb46-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-148"><a href="#cb46-148" aria-hidden="true" tabindex="-1"></a>Un equipo de monitoreo mide la concentración de clorofila-a (indicador de eutrofización) en **4 estaciones** de una bahía, con distinta influencia de escorrentía continental. Este tipo de variable ambiental suele tener una distribución muy asimétrica (muchos valores bajos, unos pocos muy altos).</span>
<span id="cb46-149"><a href="#cb46-149" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-150"><a href="#cb46-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-151"><a href="#cb46-151" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Cuántos grupos hay, y qué prueba se consideraría de entrada?</span>
<span id="cb46-152"><a href="#cb46-152" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Antes de confiar en esa prueba, ¿qué se tiene que revisar — y qué se haría si falla?</span>
<span id="cb46-153"><a href="#cb46-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-156"><a href="#cb46-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-157"><a href="#cb46-157" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb46-158"><a href="#cb46-158" aria-hidden="true" tabindex="-1"></a>estacion <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"E1_baja_escorrentia"</span>, <span class="st">"E2"</span>, <span class="st">"E3"</span>, <span class="st">"E4_alta_escorrentia"</span>))</span>
<span id="cb46-159"><a href="#cb46-159" aria-hidden="true" tabindex="-1"></a>lambda_chl <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">18</span>)[<span class="fu">as.integer</span>(estacion)]</span>
<span id="cb46-160"><a href="#cb46-160" aria-hidden="true" tabindex="-1"></a>clorofila <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rgamma</span>(<span class="dv">36</span>, <span class="at">shape =</span> <span class="fl">0.8</span>, <span class="at">rate =</span> <span class="fl">0.8</span><span class="sc">/</span>lambda_chl), <span class="dv">2</span>)</span>
<span id="cb46-161"><a href="#cb46-161" aria-hidden="true" tabindex="-1"></a>bahia_chl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(estacion, clorofila)</span>
<span id="cb46-162"><a href="#cb46-162" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl, <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb46-163"><a href="#cb46-163" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Estación"</span>, <span class="at">ylab =</span> <span class="st">"Clorofila-a (µg/L)"</span>)</span>
<span id="cb46-164"><a href="#cb46-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-165"><a href="#cb46-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-166"><a href="#cb46-166" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-167"><a href="#cb46-167" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-168"><a href="#cb46-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-169"><a href="#cb46-169" aria-hidden="true" tabindex="-1"></a>**4 grupos → candidato inicial: ANOVA.** Pero primero se revisa:</span>
<span id="cb46-170"><a href="#cb46-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-173"><a href="#cb46-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-174"><a href="#cb46-174" aria-hidden="true" tabindex="-1"></a>mod_a3t2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span>
<span id="cb46-175"><a href="#cb46-175" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(mod_a3t2))</span>
<span id="cb46-176"><a href="#cb46-176" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span>
<span id="cb46-177"><a href="#cb46-177" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-178"><a href="#cb46-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-179"><a href="#cb46-179" aria-hidden="true" tabindex="-1"></a>Ambos fallan — normalidad **y** homocedasticidad (algo muy típico en variables ambientales con distribución muy sesgada, como concentraciones o conteos). A diferencia del caso del Taller 2 (Parte 8, pargo y conectividad), donde solo fallaba la homocedasticidad, aquí falla también la normalidad — así que ni el ANOVA clásico ni el ANOVA de Welch son apropiados. La alternativa correcta es **Kruskal-Wallis**:</span>
<span id="cb46-180"><a href="#cb46-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-183"><a href="#cb46-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-184"><a href="#cb46-184" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(clorofila <span class="sc">~</span> estacion, <span class="at">data =</span> bahia_chl)</span>
<span id="cb46-185"><a href="#cb46-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-186"><a href="#cb46-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-187"><a href="#cb46-187" aria-hidden="true" tabindex="-1"></a>p = 0.00049 — diferencias claras entre estaciones. Kruskal-Wallis no exige normalidad, pero sí es sensible a dispersiones muy distintas entre grupos (aquí la desviación estándar va de 0,9 en E1 a 7,7 en E3). Por eso se interpreta como "las distribuciones de clorofila difieren entre estaciones", no estrictamente como diferencias de medianas. Para variables continuas, positivas y asimétricas como esta, la alternativa más completa es un **GLM con distribución Gamma**, que se verá en la Semana 2.</span>
<span id="cb46-188"><a href="#cb46-188" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-189"><a href="#cb46-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-190"><a href="#cb46-190" aria-hidden="true" tabindex="-1"></a><span class="fu">## A4 — Planeando un estudio: dragado y cobertura de pastos marinos {#sec-a4t2}</span></span>
<span id="cb46-191"><a href="#cb46-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-192"><a href="#cb46-192" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-193"><a href="#cb46-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### El contexto</span></span>
<span id="cb46-194"><a href="#cb46-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-195"><a href="#cb46-195" aria-hidden="true" tabindex="-1"></a>Antes de salir a campo, un equipo quiere saber cuántas parcelas necesita por grupo para detectar una diferencia de **8 puntos porcentuales** de cobertura de pastos marinos entre zonas con y sin actividad de dragado reciente, con una potencia del 80%. Un estudio piloto previo, en un sistema similar, reportó una desviación estándar de 11 puntos porcentuales.</span>
<span id="cb46-196"><a href="#cb46-196" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-197"><a href="#cb46-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-198"><a href="#cb46-198" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Qué función de R (de las usadas en la Parte 7 del taller) responde esta pregunta?</span>
<span id="cb46-199"><a href="#cb46-199" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Qué le pasaría al <span class="in">`n`</span> necesario si la variabilidad del sistema fuera mayor (sd = 15 en vez de 11)?</span>
<span id="cb46-200"><a href="#cb46-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-201"><a href="#cb46-201" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-202"><a href="#cb46-202" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-203"><a href="#cb46-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-206"><a href="#cb46-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-207"><a href="#cb46-207" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="dv">8</span>, <span class="at">sd =</span> <span class="dv">11</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span>
<span id="cb46-208"><a href="#cb46-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-209"><a href="#cb46-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-210"><a href="#cb46-210" aria-hidden="true" tabindex="-1"></a>n ≈ 31 parcelas por grupo. Se compara con una variabilidad mayor:</span>
<span id="cb46-211"><a href="#cb46-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-214"><a href="#cb46-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-215"><a href="#cb46-215" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="dv">8</span>, <span class="at">sd =</span> <span class="dv">15</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span>
<span id="cb46-216"><a href="#cb46-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-217"><a href="#cb46-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-218"><a href="#cb46-218" aria-hidden="true" tabindex="-1"></a>Con sd = 15, el <span class="in">`n`</span> necesario sube a ≈57 por grupo — más del doble. Cuanto más "ruidoso" es el sistema, más réplicas se necesitan para detectar la misma diferencia con la misma confianza. Por eso vale la pena usar la variabilidad de un piloto real (o de la literatura de la línea de investigación) en vez de inventar un número.</span>
<span id="cb46-219"><a href="#cb46-219" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-220"><a href="#cb46-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-221"><a href="#cb46-221" aria-hidden="true" tabindex="-1"></a>------------</span>
<span id="cb46-222"><a href="#cb46-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-223"><a href="#cb46-223" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb46-224"><a href="#cb46-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-225"><a href="#cb46-225" aria-hidden="true" tabindex="-1"></a><span class="fu"># Parte B — Identificación del error: diagnóstico de errores de inferencia</span></span>
<span id="cb46-226"><a href="#cb46-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-227"><a href="#cb46-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb46-228"><a href="#cb46-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.75\\linewidth"</span></span>
<span id="cb46-229"><a href="#cb46-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb46-230"><a href="#cb46-230" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb46-231"><a href="#cb46-231" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"fig_portadas/guia_refuerzo/guia_parteB.png"</span>)</span>
<span id="cb46-232"><a href="#cb46-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-233"><a href="#cb46-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-234"><a href="#cb46-234" aria-hidden="true" tabindex="-1"></a>Cada viñeta muestra un análisis ya "corrido". Conviene identificar qué está mal antes de ver la respuesta.</span>
<span id="cb46-235"><a href="#cb46-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-236"><a href="#cb46-236" aria-hidden="true" tabindex="-1"></a><span class="fu">## B1 — Tiempo de manipuleo en tres zonas de pesca {#sec-b1t2}</span></span>
<span id="cb46-237"><a href="#cb46-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-238"><a href="#cb46-238" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-239"><a href="#cb46-239" aria-hidden="true" tabindex="-1"></a><span class="fu">### La viñeta</span></span>
<span id="cb46-240"><a href="#cb46-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-241"><a href="#cb46-241" aria-hidden="true" tabindex="-1"></a>Un investigador compara el tiempo de manipuleo de la captura entre pesca artesanal, semi-industrial e industrial (3 zonas). Sin revisar ningún supuesto, corrió directamente un ANOVA de una vía, obtuvo p = 0.0585, y concluyó que **no hay diferencias** entre tipos de pesca.</span>
<span id="cb46-242"><a href="#cb46-242" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-243"><a href="#cb46-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-246"><a href="#cb46-246" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-247"><a href="#cb46-247" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb46-248"><a href="#cb46-248" aria-hidden="true" tabindex="-1"></a>zona_pesca <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">3</span>, <span class="dv">12</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Artesanal"</span>, <span class="st">"Semi_industrial"</span>, <span class="st">"Industrial"</span>))</span>
<span id="cb46-249"><a href="#cb46-249" aria-hidden="true" tabindex="-1"></a>lambda_b1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">7</span>)[<span class="fu">as.integer</span>(zona_pesca)]</span>
<span id="cb46-250"><a href="#cb46-250" aria-hidden="true" tabindex="-1"></a>tiempo_manipuleo <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rexp</span>(<span class="dv">36</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span>lambda_b1), <span class="dv">1</span>)</span>
<span id="cb46-251"><a href="#cb46-251" aria-hidden="true" tabindex="-1"></a>manipuleo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(zona_pesca, tiempo_manipuleo)</span>
<span id="cb46-252"><a href="#cb46-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-253"><a href="#cb46-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-254"><a href="#cb46-254" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Qué le faltó revisar antes de confiar en ese ANOVA?</span>
<span id="cb46-255"><a href="#cb46-255" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Cambia la conclusión si se revisa?</span>
<span id="cb46-256"><a href="#cb46-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-257"><a href="#cb46-257" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-258"><a href="#cb46-258" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-259"><a href="#cb46-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-260"><a href="#cb46-260" aria-hidden="true" tabindex="-1"></a>**Error: se saltó el diagnóstico de normalidad.** El tiempo de manipuleo, como muchas variables de tiempo, tiene una distribución muy sesgada (no negativa, cola larga a la derecha) — exactamente el tipo de variable que rara vez es normal.</span>
<span id="cb46-261"><a href="#cb46-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-264"><a href="#cb46-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-265"><a href="#cb46-265" aria-hidden="true" tabindex="-1"></a>mod_b1t2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(tiempo_manipuleo <span class="sc">~</span> zona_pesca, <span class="at">data =</span> manipuleo)</span>
<span id="cb46-266"><a href="#cb46-266" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(mod_b1t2))</span>
<span id="cb46-267"><a href="#cb46-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-268"><a href="#cb46-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-269"><a href="#cb46-269" aria-hidden="true" tabindex="-1"></a>W bajo, p = 6.9e-06 — normalidad claramente violada. Con eso en mente, la prueba correcta es Kruskal-Wallis, no el ANOVA que ya se corrió:</span>
<span id="cb46-270"><a href="#cb46-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-273"><a href="#cb46-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-274"><a href="#cb46-274" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(tiempo_manipuleo <span class="sc">~</span> zona_pesca, <span class="at">data =</span> manipuleo)</span>
<span id="cb46-275"><a href="#cb46-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-276"><a href="#cb46-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-277"><a href="#cb46-277" aria-hidden="true" tabindex="-1"></a>**La conclusión cambia:** el ANOVA (mal aplicado) daba p = 0.0585, "no significativo" — pero Kruskal-Wallis, la prueba que sí respeta la falta de normalidad, da p = 0.0217, **significativo**. Al saltarse el diagnóstico, el investigador estuvo a punto de perderse un efecto real.</span>
<span id="cb46-278"><a href="#cb46-278" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-279"><a href="#cb46-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-280"><a href="#cb46-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## B2 — "No significativo" interpretado como "no hay efecto" {#sec-b2t2}</span></span>
<span id="cb46-281"><a href="#cb46-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-282"><a href="#cb46-282" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-283"><a href="#cb46-283" aria-hidden="true" tabindex="-1"></a><span class="fu">### La viñeta</span></span>
<span id="cb46-284"><a href="#cb46-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-285"><a href="#cb46-285" aria-hidden="true" tabindex="-1"></a>Un equipo comparó un sitio control contra un sitio con impacto antrópico reciente, con solo **6 réplicas por grupo** (limitación de tiempo de campo). El t-test dio p = 0.25, y el equipo concluyó en su informe: *"no hay evidencia de que el impacto antrópico afecte la variable medida"*.</span>
<span id="cb46-286"><a href="#cb46-286" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-287"><a href="#cb46-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-290"><a href="#cb46-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-291"><a href="#cb46-291" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb46-292"><a href="#cb46-292" aria-hidden="true" tabindex="-1"></a>n_chico <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb46-293"><a href="#cb46-293" aria-hidden="true" tabindex="-1"></a>sitio_control <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_chico, <span class="at">mean =</span> <span class="dv">40</span>, <span class="at">sd =</span> <span class="dv">9</span>), <span class="dv">1</span>)</span>
<span id="cb46-294"><a href="#cb46-294" aria-hidden="true" tabindex="-1"></a>sitio_impacto <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_chico, <span class="at">mean =</span> <span class="dv">34</span>, <span class="at">sd =</span> <span class="dv">9</span>), <span class="dv">1</span>)</span>
<span id="cb46-295"><a href="#cb46-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-296"><a href="#cb46-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-297"><a href="#cb46-297" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Con solo 6 réplicas por grupo, ¿qué tan probable es que el estudio detecte un efecto moderado aunque exista de verdad?</span>
<span id="cb46-298"><a href="#cb46-298" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Es correcto decir que "no hay efecto", o sería más preciso decir otra cosa?</span>
<span id="cb46-299"><a href="#cb46-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-300"><a href="#cb46-300" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-301"><a href="#cb46-301" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-302"><a href="#cb46-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-303"><a href="#cb46-303" aria-hidden="true" tabindex="-1"></a>**Error: confundir "no se encontró evidencia significativa" con "se demostró que no hay efecto".** Un p-valor alto no prueba la hipótesis nula — solo dice que, con estos datos, no hubo evidencia suficiente para rechazarla.</span>
<span id="cb46-304"><a href="#cb46-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-307"><a href="#cb46-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-308"><a href="#cb46-308" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sitio_control, sitio_impacto)</span>
<span id="cb46-309"><a href="#cb46-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-310"><a href="#cb46-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-311"><a href="#cb46-311" aria-hidden="true" tabindex="-1"></a>Con n = 6 por grupo, se calcula qué tan probable era detectar una diferencia real de esa magnitud:</span>
<span id="cb46-312"><a href="#cb46-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-315"><a href="#cb46-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-316"><a href="#cb46-316" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n =</span> n_chico, <span class="at">delta =</span> <span class="dv">6</span>, <span class="at">sd =</span> <span class="dv">9</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>)</span>
<span id="cb46-317"><a href="#cb46-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-318"><a href="#cb46-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-319"><a href="#cb46-319" aria-hidden="true" tabindex="-1"></a>Potencia ≈ 18%. Con esa potencia, aunque el impacto antrópico **sí** tuviera un efecto real de esa magnitud, el estudio tenía más de 4 de cada 5 probabilidades de **no** detectarlo. La conclusión correcta no es "no hay efecto" — es "este estudio, con este tamaño de muestra, no tuvo potencia suficiente para detectar un efecto de esta magnitud si existiera". La diferencia es enorme para un informe técnico o un artículo.</span>
<span id="cb46-320"><a href="#cb46-320" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-321"><a href="#cb46-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-322"><a href="#cb46-322" aria-hidden="true" tabindex="-1"></a><span class="fu">## B3 — Ignorar el pareo {#sec-b3t2}</span></span>
<span id="cb46-323"><a href="#cb46-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-324"><a href="#cb46-324" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-325"><a href="#cb46-325" aria-hidden="true" tabindex="-1"></a><span class="fu">### La viñeta</span></span>
<span id="cb46-326"><a href="#cb46-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-327"><a href="#cb46-327" aria-hidden="true" tabindex="-1"></a>Retomando el diseño de A2 (mismos sitios, antes/después), un asistente de investigación analizó los datos con un t-test de dos muestras **independientes**, en vez de pareado, "porque son solo dos columnas de números".</span>
<span id="cb46-328"><a href="#cb46-328" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-329"><a href="#cb46-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-332"><a href="#cb46-332" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-333"><a href="#cb46-333" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb46-334"><a href="#cb46-334" aria-hidden="true" tabindex="-1"></a>n_par <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb46-335"><a href="#cb46-335" aria-hidden="true" tabindex="-1"></a>antes_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_par, <span class="at">mean =</span> <span class="dv">25</span>, <span class="at">sd =</span> <span class="dv">6</span>), <span class="dv">1</span>)</span>
<span id="cb46-336"><a href="#cb46-336" aria-hidden="true" tabindex="-1"></a>cambio_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_par, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="fl">1.5</span>), <span class="dv">1</span>)</span>
<span id="cb46-337"><a href="#cb46-337" aria-hidden="true" tabindex="-1"></a>despues_b3 <span class="ot">&lt;-</span> <span class="fu">round</span>(antes_b3 <span class="sc">-</span> cambio_b3, <span class="dv">1</span>)</span>
<span id="cb46-338"><a href="#cb46-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-339"><a href="#cb46-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-340"><a href="#cb46-340" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿Qué información usa el t-test pareado que el independiente ignora por completo?</span>
<span id="cb46-341"><a href="#cb46-341" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Qué se espera que le pase a la conclusión si se tratan datos pareados como independientes?</span>
<span id="cb46-342"><a href="#cb46-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-343"><a href="#cb46-343" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-344"><a href="#cb46-344" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-345"><a href="#cb46-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-346"><a href="#cb46-346" aria-hidden="true" tabindex="-1"></a>**Error: tratar datos pareados (mismo sitio medido dos veces) como si fueran dos grupos independientes.** El t-test independiente ignora que cada par de valores viene del mismo sitio — trata la variabilidad *entre sitios* como si fuera parte del "ruido" de la comparación, cuando en realidad no tiene nada que ver con el cambio antes/después.</span>
<span id="cb46-347"><a href="#cb46-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-350"><a href="#cb46-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-351"><a href="#cb46-351" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Pareado (correcto):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-352"><a href="#cb46-352" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(antes_b3, despues_b3, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-353"><a href="#cb46-353" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Independiente (incorrecto):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-354"><a href="#cb46-354" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(antes_b3, despues_b3, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb46-355"><a href="#cb46-355" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-356"><a href="#cb46-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-357"><a href="#cb46-357" aria-hidden="true" tabindex="-1"></a>**La conclusión cambia por completo:** pareado da p = 6.2e-06 (altamente significativo); tratado como independiente da p = 0.078, **no significativo** al nivel usual de 0.05. Con los mismos datos, el error de no parear pudo haber llevado a reportar "no hay evidencia de cambio" cuando en realidad el cambio es muy claro — simplemente estaba oculto por la variabilidad entre sitios, que el pareo remueve.</span>
<span id="cb46-358"><a href="#cb46-358" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-359"><a href="#cb46-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-360"><a href="#cb46-360" aria-hidden="true" tabindex="-1"></a><span class="fu">## B4 — Comparaciones múltiples sin corrección {#sec-b4t2}</span></span>
<span id="cb46-361"><a href="#cb46-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-362"><a href="#cb46-362" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb46-363"><a href="#cb46-363" aria-hidden="true" tabindex="-1"></a><span class="fu">### La viñeta</span></span>
<span id="cb46-364"><a href="#cb46-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-365"><a href="#cb46-365" aria-hidden="true" tabindex="-1"></a>Un estudiante compara una variable entre 4 grupos experimentales. En vez de correr un solo ANOVA, decidió correr un **t-test independiente para cada par posible de grupos** (6 comparaciones en total), y reportó como "hallazgo" la única comparación que dio p <span class="sc">\&lt;</span> 0.05.</span>
<span id="cb46-366"><a href="#cb46-366" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-367"><a href="#cb46-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-370"><a href="#cb46-370" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-371"><a href="#cb46-371" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb46-372"><a href="#cb46-372" aria-hidden="true" tabindex="-1"></a>grupo_b4 <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">4</span>, <span class="dv">10</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>, <span class="st">"G4"</span>))</span>
<span id="cb46-373"><a href="#cb46-373" aria-hidden="true" tabindex="-1"></a>valor_b4 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd =</span> <span class="dv">5</span>), <span class="dv">1</span>)</span>
<span id="cb46-374"><a href="#cb46-374" aria-hidden="true" tabindex="-1"></a>datos_b4 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(grupo_b4, valor_b4)</span>
<span id="cb46-375"><a href="#cb46-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-376"><a href="#cb46-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-377"><a href="#cb46-377" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Si se repite una prueba con α = 0.05 muchas veces, aunque no exista ningún efecto real, ¿qué probabilidad hay de que **al menos una** salga "significativa" solo por azar?</span>
<span id="cb46-378"><a href="#cb46-378" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>¿Qué debió haberse corrido en su lugar?</span>
<span id="cb46-379"><a href="#cb46-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-380"><a href="#cb46-380" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb46-381"><a href="#cb46-381" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación del razonamiento</span></span>
<span id="cb46-382"><a href="#cb46-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-383"><a href="#cb46-383" aria-hidden="true" tabindex="-1"></a>**Error: comparaciones múltiples sin corrección, inflando el error tipo I.** Cada t-test individual tiene 5% de probabilidad de un falso positivo — pero con 6 comparaciones, la probabilidad de que **al menos una** salga significativa por puro azar es mucho mayor a 5%.</span>
<span id="cb46-384"><a href="#cb46-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-385"><a href="#cb46-385" aria-hidden="true" tabindex="-1"></a>En esta simulación, **no se programó ninguna diferencia real entre los 4 grupos** (misma media, mismo sd). Aun así:</span>
<span id="cb46-386"><a href="#cb46-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-389"><a href="#cb46-389" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-390"><a href="#cb46-390" aria-hidden="true" tabindex="-1"></a>niveles <span class="ot">&lt;-</span> <span class="fu">levels</span>(grupo_b4)</span>
<span id="cb46-391"><a href="#cb46-391" aria-hidden="true" tabindex="-1"></a>pares <span class="ot">&lt;-</span> <span class="fu">combn</span>(niveles, <span class="dv">2</span>)</span>
<span id="cb46-392"><a href="#cb46-392" aria-hidden="true" tabindex="-1"></a>ps <span class="ot">&lt;-</span> <span class="fu">apply</span>(pares, <span class="dv">2</span>, <span class="cf">function</span>(p) {</span>
<span id="cb46-393"><a href="#cb46-393" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(valor_b4[grupo_b4 <span class="sc">==</span> p[<span class="dv">1</span>]], valor_b4[grupo_b4 <span class="sc">==</span> p[<span class="dv">2</span>]])<span class="sc">$</span>p.value</span>
<span id="cb46-394"><a href="#cb46-394" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb46-395"><a href="#cb46-395" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ps) <span class="ot">&lt;-</span> <span class="fu">apply</span>(pares, <span class="dv">2</span>, paste, <span class="at">collapse =</span> <span class="st">" vs "</span>)</span>
<span id="cb46-396"><a href="#cb46-396" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ps, <span class="dv">4</span>)</span>
<span id="cb46-397"><a href="#cb46-397" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-398"><a href="#cb46-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-399"><a href="#cb46-399" aria-hidden="true" tabindex="-1"></a>Una comparación (G1 vs G3) sale "significativa" (p = 0.019) — puro azar, disfrazado de hallazgo. El ANOVA de una vía, la prueba diseñada para comparar los 4 grupos a la vez con un solo error tipo I controlado, correctamente **no** detecta diferencias:</span>
<span id="cb46-400"><a href="#cb46-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-403"><a href="#cb46-403" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb46-404"><a href="#cb46-404" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(valor_b4 <span class="sc">~</span> grupo_b4, <span class="at">data =</span> datos_b4))</span>
<span id="cb46-405"><a href="#cb46-405" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb46-406"><a href="#cb46-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-407"><a href="#cb46-407" aria-hidden="true" tabindex="-1"></a>**La lección:** cuando se quiere comparar más de 2 grupos, se corre primero un ANOVA (o Kruskal-Wallis), no una serie de t-tests de a pares. Si el ANOVA es significativo y se necesita saber cuáles pares difieren, existen comparaciones post-hoc (como <span class="in">`TukeyHSD()`</span>, que se usa en la Parte 4 del Taller 2) diseñadas específicamente para controlar el error acumulado — correr t-tests sueltos no lo hace.</span>
<span id="cb46-408"><a href="#cb46-408" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb46-409"><a href="#cb46-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-410"><a href="#cb46-410" aria-hidden="true" tabindex="-1"></a><span class="fu"># Cierre</span></span>
<span id="cb46-411"><a href="#cb46-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-412"><a href="#cb46-412" aria-hidden="true" tabindex="-1"></a>Estos 8 ejercicios apuntan a la misma habilidad desde ángulos distintos: elegir la herramienta de inferencia correcta para cada pregunta, y reconocer cuándo un análisis —propio o ajeno— tiene un problema que ningún p-valor bonito puede tapar. Es exactamente el tipo de revisión que un jurado de tesis, o un revisor de artículo, le hará al propio trabajo — mejor practicarlo ahora, con datos simulados, que descubrirlo tarde con los datos propios.</span>
<span id="cb46-413"><a href="#cb46-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-414"><a href="#cb46-414" aria-hidden="true" tabindex="-1"></a><span class="fu">## Referencias</span></span>
<span id="cb46-415"><a href="#cb46-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-416"><a href="#cb46-416" aria-hidden="true" tabindex="-1"></a>Los escenarios de esta guía son de elaboración propia para este curso; no reproducen ejercicios ni datos de las fuentes citadas en el Taller 2.</span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>