<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ES-es" xml:lang="ES-es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Rodríguez-Barrios">

<title>Cuestionario de Refuerzo · GLM Binomial y Poisson</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Cuestionario2_GLM_files/libs/clipboard/clipboard.min.js"></script>
<script src="Cuestionario2_GLM_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Cuestionario2_GLM_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Cuestionario2_GLM_files/libs/quarto-html/popper.min.js"></script>
<script src="Cuestionario2_GLM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Cuestionario2_GLM_files/libs/quarto-html/anchor.min.js"></script>
<link href="Cuestionario2_GLM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Cuestionario2_GLM_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Cuestionario2_GLM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Cuestionario2_GLM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Cuestionario2_GLM_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner {
        background: #2098D9;
      }
</style>


</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Cuestionario de Refuerzo · GLM Binomial y Poisson</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
            <p class="subtitle lead">Bioestadística · Semana 2 · 2026-II</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://www.unimagdalena.edu.co/">Javier Rodríguez-Barrios</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">3 de octubre de 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#bloque-a-conceptos" id="toc-bloque-a-conceptos" class="nav-link active" data-scroll-target="#bloque-a-conceptos">Bloque A — Conceptos</a></li>
  <li><a href="#sec-rhodophyta" id="toc-sec-rhodophyta" class="nav-link" data-scroll-target="#sec-rhodophyta">Bloque B — Ocupación de macroalgas Rhodophyta y profundidad</a></li>
  <li><a href="#sec-bentos-glm" id="toc-sec-bentos-glm" class="nav-link" data-scroll-target="#sec-bentos-glm">Bloque C — Abundancia bentónica y perturbación antrópica</a></li>
  <li><a href="#sec-familia" id="toc-sec-familia" class="nav-link" data-scroll-target="#sec-familia">Bloque D — ¿Qué familia se usa?</a></li>
  <li><a href="#bloque-e-proyecto-de-grado" id="toc-bloque-e-proyecto-de-grado" class="nav-link" data-scroll-target="#bloque-e-proyecto-de-grado">Bloque E — Proyecto de grado</a></li>
  <li><a href="#retroalimentación" id="toc-retroalimentación" class="nav-link" data-scroll-target="#retroalimentación">Retroalimentación</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/cuestionarios/1_refuerzo_glm_portada.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:85.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cómo usar este cuestionario
</div>
</div>
<div class="callout-body-container callout-body">
<p>Autoevaluación (RA1, RA2) para después del <code>Taller · GLM Binomial y Poisson en R</code> y del cuestionario de opción múltiple. Los escenarios <strong>no son los mismos</strong> del taller: usan otros datos, para razonar el resultado en lugar de recordarlo. La retroalimentación completa está al final.</p>
</div>
</div>
<hr>
<section id="bloque-a-conceptos" class="level2">
<h2 class="anchored" data-anchor-id="bloque-a-conceptos">Bloque A — Conceptos</h2>
<p><strong>A1.</strong> ¿Por qué no basta con ajustar <code>lm()</code> a una variable de presencia/ausencia (0/1)? Mencionar un problema concreto de las predicciones.</p>
<p><strong>A2.</strong> En un GLM, ¿sobre qué actúa la función de enlace: sobre cada observación de Y (como una transformación clásica) o sobre otra cosa? Explicar la diferencia y una ventaja práctica cuando hay ceros.</p>
<p><strong>A3.</strong> Un colega reporta un GLM binomial con β = 0.10 y afirma que “el efecto es pequeño”. ¿Qué falta antes de que esa afirmación tenga sentido?</p>
<p><strong>A4.</strong> ¿Qué mide φ (phi) en un GLM Poisson, cómo se calcula y qué decisión se tomaría si φ = 3.5?</p>
<p><strong>A5.</strong> Un GLM binomial arroja p = 0.003 para el predictor, pero la devianza solo se reduce un 8 %. ¿Es contradictorio? Explicar.</p>
<hr>
</section>
<section id="sec-rhodophyta" class="level2">
<h2 class="anchored" data-anchor-id="sec-rhodophyta">Bloque B — Ocupación de macroalgas Rhodophyta y profundidad</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/cuestionarios/2_refuerzo_glm_bloqueB_rhodophyta.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p>Una estudiante registra la presencia/ausencia de un banco de Rhodophyta en 50 cuadrantes a distinta profundidad y ajusta un GLM binomial:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Coeficiente</th>
<th>Estimado</th>
<th>OR = exp(β)</th>
<th>IC 95 % (OR)</th>
<th>Valor p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercepto</td>
<td>1.645</td>
<td>—</td>
<td>—</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>Profundidad (m)</td>
<td>−0.154</td>
<td>0.857</td>
<td>[0.760, 0.952]</td>
<td>0.007</td>
</tr>
</tbody>
</table>
<p>n = 50 cuadrantes, 27 ocupados.</p>
<p><strong>B1.</strong> Escribir la ecuación logit del modelo e interpretar el signo del coeficiente de profundidad en términos biológicos (pista: disponibilidad de luz).</p>
<p><strong>B2.</strong> El IC del OR es [0.760, 0.952] y no incluye 1. ¿Qué indica sobre la relación entre profundidad y ocupación?</p>
<p><strong>B3.</strong> Calcular la probabilidad de ocupación predicha a 5 m y a 15 m de profundidad (con la ecuación logit y <code>plogis()</code>, o a mano).</p>
<p><strong>B4.</strong> Si OR = 0.857 significa que “por cada metro adicional, los odds de ocupación se multiplican por 0.857”, ¿por qué NO es correcto afirmar que “la ocupación baja un 14.3 % por metro”? (pista: diferencia entre <em>odds</em> y <em>probabilidad</em>).</p>
<hr>
</section>
<section id="sec-bentos-glm" class="level2">
<h2 class="anchored" data-anchor-id="sec-bentos-glm">Bloque C — Abundancia bentónica y perturbación antrópica</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/cuestionarios/3_refuerzo_glm_bloqueC_bentos.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p>Un estudiante cuenta organismos bentónicos por núcleo de sedimento en 34 estaciones con distinto nivel de perturbación antrópica (índice 0–10) y ajusta un GLM Poisson:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coeficiente</th>
<th>Estimado</th>
<th>Razón de tasas</th>
<th>Valor p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercepto</td>
<td>2.146</td>
<td>—</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>Perturbación</td>
<td>−0.056</td>
<td>0.946</td>
<td>0.013</td>
</tr>
</tbody>
</table>
<p>n = 34, φ = 1.56, AIC = 176.0</p>
<p><strong>C1.</strong> Interpretar la razón de tasas (0.946) en una frase, en el contexto de perturbación antrópica y comunidades bentónicas.</p>
<p><strong>C2.</strong> φ = 1.56 está dentro de la zona de alerta vista en clase (φ ≈ 1: equidispersión; φ &gt; 1.2–2: sobredispersión), aunque lejos del ejemplo del arrecife en el taller (φ = 2.22). ¿Se mantendría el Poisson o se corregiría? Justificar.</p>
<p><strong>C3.</strong> Si se ajustara <code>MASS::glm.nb()</code> en lugar de <code>glm(family = poisson)</code>, ¿se esperaría que el coeficiente de perturbación cambie mucho? ¿Qué sí se esperaría que cambie?</p>
<hr>
</section>
<section id="sec-familia" class="level2">
<h2 class="anchored" data-anchor-id="sec-familia">Bloque D — ¿Qué familia se usa?</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/cuestionarios/4_refuerzo_glm_bloqueD_familias.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p>Para cada situación, indicar familia GLM, función de enlace y cualquier detalle adicional del modelo:</p>
<p><strong>D1.</strong> Proporción de cobertura de coral vivo por cuadrante, medida como puntos con coral / total de puntos muestreados.</p>
<p><strong>D2.</strong> Número de nidos de tortuga marina por temporada en segmentos de playa de longitud distinta.</p>
<p><strong>D3.</strong> Presencia/ausencia de manatí antillano en estaciones de monitoreo de un río.</p>
<p><strong>D4.</strong> Longitud total (cm) de individuos de jurel capturados en un muestreo pesquero.</p>
<hr>
</section>
<section id="bloque-e-proyecto-de-grado" class="level2">
<h2 class="anchored" data-anchor-id="bloque-e-proyecto-de-grado">Bloque E — Proyecto de grado</h2>
<p><strong>E1.</strong> Describir en una frase una variable respuesta del propio proyecto de grado que requeriría un GLM (y no <code>lm()</code>). Indicar familia y enlace.</p>
<p><strong>E2.</strong> Si esa variable es un conteo, ¿qué proceso biológico del sistema podría generar sobredispersión (agregación, parches, exceso de ceros)? ¿El esfuerzo de muestreo es igual entre unidades o requeriría offset?</p>
<hr>
</section>
<section id="retroalimentación" class="level2">
<h2 class="anchored" data-anchor-id="retroalimentación">Retroalimentación</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ver respuestas y justificación
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>A1.</strong> Una recta puede predecir valores fuera de [0, 1]: probabilidades negativas o mayores que 1, que no tienen sentido para una variable binaria. Además, los residuos de datos 0/1 no son normales y su varianza, p(1 − p), depende de la media.</p>
<p><strong>A2.</strong> Actúa sobre μ = E(Y), el valor esperado, no sobre cada observación. Por eso la varianza se modela en su escala real. Ventaja práctica: un conteo de 0 no genera problema, mientras que log(Y) de un 0 es −∞ y obliga a recursos como log(Y + 1).</p>
<p><strong>A3.</strong> Falta la escala: β = 0.10 está en escala logit. Hay que exponenciarlo (OR = exp(0.10) ≈ 1.105, +10.5 % en los odds por unidad de X) y considerar el rango de X: a lo largo de 20 unidades, el OR acumulado sería exp(2) ≈ 7.4, un efecto grande.</p>
<p><strong>A4.</strong> φ compara la variabilidad observada con la esperada bajo Poisson. Se calcula como la suma de los residuos de Pearson al cuadrado dividida por los g.l. residuales (la razón devianza residual / g.l. es una aproximación). Con φ = 3.5 hay sobredispersión fuerte: los errores estándar del Poisson están subestimados. Conviene ajustar <code>MASS::glm.nb()</code> (o cuasi-Poisson) y revisar posibles causas biológicas (agregación, covariables omitidas, exceso de ceros).</p>
<p><strong>A5.</strong> No es contradictorio. El valor p indica que el efecto es distinguible del azar; la reducción de devianza indica cuánto de la variación explica el predictor. Un efecto puede ser real y a la vez explicar poco, porque otros factores no incluidos pesan más. Es el mismo razonamiento que r² frente al valor p en regresión lineal.</p>
<p><strong>B1.</strong> logit(p) = 1.645 − 0.154 × profundidad. El signo negativo indica que a mayor profundidad disminuye la probabilidad de ocupación, consistente con la menor disponibilidad de luz para la fotosíntesis.</p>
<p><strong>B2.</strong> Como el IC no incluye 1, hay evidencia estadística de que la profundidad reduce la probabilidad de ocupación. Al ser un estudio observacional, se concluye asociación y no causalidad (la profundidad covaría con luz, temperatura y sustrato).</p>
<p><strong>B3.</strong> A 5 m: logit = 1.645 − 0.154 × 5 = 0.875 → p = plogis(0.875) ≈ 0.71. A 15 m: logit = 1.645 − 0.154 × 15 = −0.665 → p = plogis(−0.665) ≈ 0.34.</p>
<p><strong>B4.</strong> El OR describe un cambio multiplicativo en los <em>odds</em> [p/(1 − p)], no en la probabilidad. La relación entre odds y probabilidad no es lineal, así que “los odds bajan 14.3 %” no se traduce en “la probabilidad baja 14.3 %”. En B3, la probabilidad cae de 71 % a 34 % entre 5 y 15 m, y la magnitud del cambio por metro depende del tramo de la curva.</p>
<p><strong>C1.</strong> Por cada unidad adicional del índice de perturbación, la abundancia esperada de organismos bentónicos se multiplica por 0.946, es decir, disminuye un 5.4 %. Es consistente con la degradación del hábitat bentónico por presión humana.</p>
<p><strong>C2.</strong> Lo más prudente es corregir o, al menos, reportar ambos modelos. Con estos datos, la binomial negativa da el mismo coeficiente (−0.056), un error estándar mayor (0.027 frente a 0.023) y p = 0.037 en lugar de 0.013. El AIC apenas cambia (175.3 frente a 176.0; ΔAIC &lt; 2, modelos prácticamente equivalentes). La conclusión se mantiene, pero con una evidencia menos exagerada. Dejarlo como Poisson solo se justificaría en un análisis exploratorio.</p>
<p><strong>C3.</strong> El coeficiente cambiaría poco: la binomial negativa suele dar una estimación puntual similar a la del Poisson. Lo que sí cambia es el <strong>error estándar</strong>, que crece porque ya no se asume Var = μ. En consecuencia, el valor p aumenta y el IC se ensancha.</p>
<p><strong>D1.</strong> Binomial con enlace logit, usando <code>cbind(puntos_coral, puntos_sin_coral)</code> como respuesta, no el porcentaje. Como los puntos de un mismo cuadrante no son independientes, es frecuente encontrar sobredispersión: en ese caso, <code>family = quasibinomial</code>.</p>
<p><strong>D2.</strong> Poisson (o binomial negativa si hay sobredispersión) con enlace log. Como los segmentos tienen longitudes distintas, se incluye <code>offset(log(longitud_km))</code> para modelar nidos por km.</p>
<p><strong>D3.</strong> Binomial con enlace logit (presencia/ausencia).</p>
<p><strong>D4.</strong> Gaussiana con enlace identidad: una variable continua y aproximadamente normal se analiza con <code>lm()</code> (equivalente a <code>glm(family = gaussian)</code>).</p>
<p><strong>E1 y E2.</strong> No hay respuesta única: contrastar el razonamiento con el profesor o los compañeros.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<ul>
<li><p>Quinn, G. P., &amp; Keough, M. J. (2024). <em>Experimental Design and Data Analysis for Biologists</em> (2nd ed.). Cambridge University Press. <a href="https://mjkeough.github.io/examples.html">enlace_ejercicios</a></p></li>
<li><p>Logan, M. (2011). <em>Biostatistical Design and Analysis Using R</em>. Wiley-Blackwell. <a href="https://bcs.wiley.com/he-bcs/Books?action=index&amp;bcsId=5684&amp;itemId=1405190086">enlace_ejercicios</a>; <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781444319620">enlace_libro</a></p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los escenarios de este cuestionario son de elaboración propia; sus cifras se reproducen con datos simulados en R (script de respaldo del docente) y no reproducen ejercicios de las fuentes citadas.</p>
</div>
</div>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Cuestionario de Refuerzo · GLM Binomial y Poisson"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Bioestadística · Semana 2 · 2026-II"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Javier Rodríguez-Barrios</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">  url: https://www.unimagdalena.edu.co/</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">  afiliation: Grupo de Investigación</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">  afiliation-url: https://</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner:</span><span class="co"> "#2098D9"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true    # Tabla de contenido</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: Menú flotante</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true     # Opción para descargar los códigos</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true     # Visualización de los códigos en el reporte</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> ES-es</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>   <span class="co"># Muestra una portada. Si el paquete magick está instalado, la convierte</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>   <span class="co"># a JPG liviano (1400 px, calidad 80) la primera vez y usa esa versión;</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>   <span class="co"># si no está instalado, muestra el PNG original.</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>   portada <span class="ot">&lt;-</span> <span class="cf">function</span>(ruta, <span class="at">ancho =</span> <span class="dv">1400</span>, <span class="at">calidad =</span> <span class="dv">80</span>) {</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>     jpg <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">.png$"</span>, <span class="st">".jpg"</span>, ruta)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>     <span class="cf">if</span> (<span class="fu">requireNamespace</span>(<span class="st">"magick"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>       <span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(jpg) <span class="sc">||</span> <span class="fu">file.mtime</span>(jpg) <span class="sc">&lt;</span> <span class="fu">file.mtime</span>(ruta)) {</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>         magick<span class="sc">::</span><span class="fu">image_read</span>(ruta) <span class="sc">|&gt;</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>           magick<span class="sc">::</span><span class="fu">image_scale</span>(<span class="fu">paste0</span>(ancho, <span class="st">"&gt;"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>           magick<span class="sc">::</span><span class="fu">image_background</span>(<span class="st">"white"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>           magick<span class="sc">::</span><span class="fu">image_flatten</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>           magick<span class="sc">::</span><span class="fu">image_write</span>(jpg, <span class="at">format =</span> <span class="st">"jpeg"</span>, <span class="at">quality =</span> calidad)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>       }</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>       knitr<span class="sc">::</span><span class="fu">include_graphics</span>(jpg)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>     } <span class="cf">else</span> {</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>       knitr<span class="sc">::</span><span class="fu">include_graphics</span>(ruta)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>     }</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.85\\linewidth"</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">portada</span>(<span class="st">"figuras_portadas/cuestionarios/1_refuerzo_glm_portada.png"</span>)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cómo usar este cuestionario</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>Autoevaluación (RA1, RA2) para después del <span class="in">`Taller · GLM Binomial y Poisson en R`</span> y del cuestionario de opción múltiple. Los escenarios **no son los mismos** del taller: usan otros datos, para razonar el resultado en lugar de recordarlo. La retroalimentación completa está al final.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bloque A — Conceptos</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>**A1.** ¿Por qué no basta con ajustar <span class="in">`lm()`</span> a una variable de presencia/ausencia (0/1)? Mencionar un problema concreto de las predicciones.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>**A2.** En un GLM, ¿sobre qué actúa la función de enlace: sobre cada observación de Y (como una transformación clásica) o sobre otra cosa? Explicar la diferencia y una ventaja práctica cuando hay ceros.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>**A3.** Un colega reporta un GLM binomial con β = 0.10 y afirma que "el efecto es pequeño". ¿Qué falta antes de que esa afirmación tenga sentido?</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>**A4.** ¿Qué mide φ (phi) en un GLM Poisson, cómo se calcula y qué decisión se tomaría si φ = 3.5?</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>**A5.** Un GLM binomial arroja p = 0.003 para el predictor, pero la devianza solo se reduce un 8 %. ¿Es contradictorio? Explicar.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bloque B — Ocupación de macroalgas Rhodophyta y profundidad {#sec-rhodophyta}</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/cuestionarios/2_refuerzo_glm_bloqueB_rhodophyta.png"</span>)</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>Una estudiante registra la presencia/ausencia de un banco de Rhodophyta en 50 cuadrantes a distinta profundidad y ajusta un GLM binomial:</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Coeficiente     <span class="pp">|</span> Estimado <span class="pp">|</span> OR = exp(β) <span class="pp">|</span> IC 95 % (OR)     <span class="pp">|</span> Valor p <span class="pp">|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------------|----------|-------------|------------------|---------|</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Intercepto      <span class="pp">|</span> 1.645    <span class="pp">|</span> —           <span class="pp">|</span> —                <span class="pp">|</span> 0.009   <span class="pp">|</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Profundidad (m) <span class="pp">|</span> −0.154   <span class="pp">|</span> 0.857       <span class="pp">|</span> <span class="sc">\[</span>0.760, 0.952<span class="sc">\]</span> <span class="pp">|</span> 0.007   <span class="pp">|</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>n = 50 cuadrantes, 27 ocupados.</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>**B1.** Escribir la ecuación logit del modelo e interpretar el signo del coeficiente de profundidad en términos biológicos (pista: disponibilidad de luz).</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>**B2.** El IC del OR es <span class="sc">\[</span>0.760, 0.952<span class="sc">\]</span> y no incluye 1. ¿Qué indica sobre la relación entre profundidad y ocupación?</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>**B3.** Calcular la probabilidad de ocupación predicha a 5 m y a 15 m de profundidad (con la ecuación logit y <span class="in">`plogis()`</span>, o a mano).</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>**B4.** Si OR = 0.857 significa que "por cada metro adicional, los odds de ocupación se multiplican por 0.857", ¿por qué NO es correcto afirmar que "la ocupación baja un 14.3 % por metro"? (pista: diferencia entre *odds* y *probabilidad*).</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bloque C — Abundancia bentónica y perturbación antrópica {#sec-bentos-glm}</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/cuestionarios/3_refuerzo_glm_bloqueC_bentos.png"</span>)</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Un estudiante cuenta organismos bentónicos por núcleo de sedimento en 34 estaciones con distinto nivel de perturbación antrópica (índice 0–10) y ajusta un GLM Poisson:</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Coeficiente  <span class="pp">|</span> Estimado <span class="pp">|</span> Razón de tasas <span class="pp">|</span> Valor p  <span class="pp">|</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------------|----------|----------------|----------|</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Intercepto   <span class="pp">|</span> 2.146    <span class="pp">|</span> —              <span class="pp">|</span> <span class="sc">\&lt;</span> 0.001 <span class="pp">|</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Perturbación <span class="pp">|</span> −0.056   <span class="pp">|</span> 0.946          <span class="pp">|</span> 0.013    <span class="pp">|</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>n = 34, φ = 1.56, AIC = 176.0</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>**C1.** Interpretar la razón de tasas (0.946) en una frase, en el contexto de perturbación antrópica y comunidades bentónicas.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>**C2.** φ = 1.56 está dentro de la zona de alerta vista en clase (φ ≈ 1: equidispersión; φ <span class="sc">\&gt;</span> 1.2–2: sobredispersión), aunque lejos del ejemplo del arrecife en el taller (φ = 2.22). ¿Se mantendría el Poisson o se corregiría? Justificar.</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>**C3.** Si se ajustara <span class="in">`MASS::glm.nb()`</span> en lugar de <span class="in">`glm(family = poisson)`</span>, ¿se esperaría que el coeficiente de perturbación cambie mucho? ¿Qué sí se esperaría que cambie?</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bloque D — ¿Qué familia se usa? {#sec-familia}</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/cuestionarios/4_refuerzo_glm_bloqueD_familias.png"</span>)</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>Para cada situación, indicar familia GLM, función de enlace y cualquier detalle adicional del modelo:</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>**D1.** Proporción de cobertura de coral vivo por cuadrante, medida como puntos con coral / total de puntos muestreados.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>**D2.** Número de nidos de tortuga marina por temporada en segmentos de playa de longitud distinta.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>**D3.** Presencia/ausencia de manatí antillano en estaciones de monitoreo de un río.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>**D4.** Longitud total (cm) de individuos de jurel capturados en un muestreo pesquero.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bloque E — Proyecto de grado</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>**E1.** Describir en una frase una variable respuesta del propio proyecto de grado que requeriría un GLM (y no <span class="in">`lm()`</span>). Indicar familia y enlace.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>**E2.** Si esa variable es un conteo, ¿qué proceso biológico del sistema podría generar sobredispersión (agregación, parches, exceso de ceros)? ¿El esfuerzo de muestreo es igual entre unidades o requeriría offset?</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="fu">## Retroalimentación</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip collapse="true"}</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ver respuestas y justificación</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>**A1.** Una recta puede predecir valores fuera de <span class="sc">\[</span>0, 1<span class="sc">\]</span>: probabilidades negativas o mayores que 1, que no tienen sentido para una variable binaria. Además, los residuos de datos 0/1 no son normales y su varianza, p(1 − p), depende de la media.</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>**A2.** Actúa sobre μ = E(Y), el valor esperado, no sobre cada observación. Por eso la varianza se modela en su escala real. Ventaja práctica: un conteo de 0 no genera problema, mientras que log(Y) de un 0 es −∞ y obliga a recursos como log(Y + 1).</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>**A3.** Falta la escala: β = 0.10 está en escala logit. Hay que exponenciarlo (OR = exp(0.10) ≈ 1.105, +10.5 % en los odds por unidad de X) y considerar el rango de X: a lo largo de 20 unidades, el OR acumulado sería exp(2) ≈ 7.4, un efecto grande.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>**A4.** φ compara la variabilidad observada con la esperada bajo Poisson. Se calcula como la suma de los residuos de Pearson al cuadrado dividida por los g.l. residuales (la razón devianza residual / g.l. es una aproximación). Con φ = 3.5 hay sobredispersión fuerte: los errores estándar del Poisson están subestimados. Conviene ajustar <span class="in">`MASS::glm.nb()`</span> (o cuasi-Poisson) y revisar posibles causas biológicas (agregación, covariables omitidas, exceso de ceros).</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>**A5.** No es contradictorio. El valor p indica que el efecto es distinguible del azar; la reducción de devianza indica cuánto de la variación explica el predictor. Un efecto puede ser real y a la vez explicar poco, porque otros factores no incluidos pesan más. Es el mismo razonamiento que r² frente al valor p en regresión lineal.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>**B1.** logit(p) = 1.645 − 0.154 × profundidad. El signo negativo indica que a mayor profundidad disminuye la probabilidad de ocupación, consistente con la menor disponibilidad de luz para la fotosíntesis.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>**B2.** Como el IC no incluye 1, hay evidencia estadística de que la profundidad reduce la probabilidad de ocupación. Al ser un estudio observacional, se concluye asociación y no causalidad (la profundidad covaría con luz, temperatura y sustrato).</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>**B3.** A 5 m: logit = 1.645 − 0.154 × 5 = 0.875 → p = plogis(0.875) ≈ 0.71. A 15 m: logit = 1.645 − 0.154 × 15 = −0.665 → p = plogis(−0.665) ≈ 0.34.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>**B4.** El OR describe un cambio multiplicativo en los *odds* <span class="sc">\[</span>p/(1 − p)<span class="sc">\]</span>, no en la probabilidad. La relación entre odds y probabilidad no es lineal, así que "los odds bajan 14.3 %" no se traduce en "la probabilidad baja 14.3 %". En B3, la probabilidad cae de 71 % a 34 % entre 5 y 15 m, y la magnitud del cambio por metro depende del tramo de la curva.</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>**C1.** Por cada unidad adicional del índice de perturbación, la abundancia esperada de organismos bentónicos se multiplica por 0.946, es decir, disminuye un 5.4 %. Es consistente con la degradación del hábitat bentónico por presión humana.</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>**C2.** Lo más prudente es corregir o, al menos, reportar ambos modelos. Con estos datos, la binomial negativa da el mismo coeficiente (−0.056), un error estándar mayor (0.027 frente a 0.023) y p = 0.037 en lugar de 0.013. El AIC apenas cambia (175.3 frente a 176.0; ΔAIC <span class="sc">\&lt;</span> 2, modelos prácticamente equivalentes). La conclusión se mantiene, pero con una evidencia menos exagerada. Dejarlo como Poisson solo se justificaría en un análisis exploratorio.</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>**C3.** El coeficiente cambiaría poco: la binomial negativa suele dar una estimación puntual similar a la del Poisson. Lo que sí cambia es el **error estándar**, que crece porque ya no se asume Var = μ. En consecuencia, el valor p aumenta y el IC se ensancha.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>**D1.** Binomial con enlace logit, usando <span class="in">`cbind(puntos_coral, puntos_sin_coral)`</span> como respuesta, no el porcentaje. Como los puntos de un mismo cuadrante no son independientes, es frecuente encontrar sobredispersión: en ese caso, <span class="in">`family = quasibinomial`</span>.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>**D2.** Poisson (o binomial negativa si hay sobredispersión) con enlace log. Como los segmentos tienen longitudes distintas, se incluye <span class="in">`offset(log(longitud_km))`</span> para modelar nidos por km.</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>**D3.** Binomial con enlace logit (presencia/ausencia).</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>**D4.** Gaussiana con enlace identidad: una variable continua y aproximadamente normal se analiza con <span class="in">`lm()`</span> (equivalente a <span class="in">`glm(family = gaussian)`</span>).</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>**E1 y E2.** No hay respuesta única: contrastar el razonamiento con el profesor o los compañeros.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="fu">## Referencias</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Quinn, G. P., &amp; Keough, M. J. (2024). *Experimental Design and Data Analysis for Biologists* (2nd ed.). Cambridge University Press. <span class="co">[</span><span class="ot">enlace_ejercicios</span><span class="co">](https://mjkeough.github.io/examples.html)</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Logan, M. (2011). *Biostatistical Design and Analysis Using R*. Wiley-Blackwell. <span class="co">[</span><span class="ot">enlace_ejercicios</span><span class="co">](https://bcs.wiley.com/he-bcs/Books?action=index&amp;bcsId=5684&amp;itemId=1405190086)</span>; <span class="co">[</span><span class="ot">enlace_libro</span><span class="co">](https://onlinelibrary.wiley.com/doi/book/10.1002/9781444319620)</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>Los escenarios de este cuestionario son de elaboración propia; sus cifras se reproducen con datos simulados en R (script de respaldo del docente) y no reproducen ejercicios de las fuentes citadas.</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>