<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ES-es" xml:lang="ES-es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nombre del Estudiante">

<title>Taller · GLM Binomial y Poisson en R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Taller4_GLM_Binomial_Poisson_files/libs/clipboard/clipboard.min.js"></script>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/popper.min.js"></script>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/anchor.min.js"></script>
<link href="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Taller4_GLM_Binomial_Poisson_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Taller4_GLM_Binomial_Poisson_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Taller4_GLM_Binomial_Poisson_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Taller4_GLM_Binomial_Poisson_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner {
        background: #2098D9;
      }
</style>
<script src="Taller4_GLM_Binomial_Poisson_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Taller4_GLM_Binomial_Poisson_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Taller · GLM Binomial y Poisson en R</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
            <p class="subtitle lead">Bioestadística · Semana 2 · 2026-II</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://www.unimagdalena.edu.co/">Nombre del Estudiante</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">4 de octubre de 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#materiales-requeridos-para-el-taller-en-clase" id="toc-materiales-requeridos-para-el-taller-en-clase" class="nav-link active" data-scroll-target="#materiales-requeridos-para-el-taller-en-clase">Materiales requeridos para el taller en clase</a>
  <ul class="collapse">
  <li><a href="#diapositivas-en-vivo---slides.com" id="toc-diapositivas-en-vivo---slides.com" class="nav-link" data-scroll-target="#diapositivas-en-vivo---slides.com">Diapositivas en vivo - Slides.com</a></li>
  </ul></li>
  <li><a href="#objetivos-del-taller" id="toc-objetivos-del-taller" class="nav-link" data-scroll-target="#objetivos-del-taller">Objetivos del taller</a></li>
  <li><a href="#sec-fundamentos" id="toc-sec-fundamentos" class="nav-link" data-scroll-target="#sec-fundamentos">Antes de empezar: ¿qué es un GLM?</a></li>
  <li><a href="#sec-binomial" id="toc-sec-binomial" class="nav-link" data-scroll-target="#sec-binomial">Parte 1 — GLM binomial: enfermedad de coral y temperatura</a>
  <ul class="collapse">
  <li><a href="#prueba-de-razón-de-verosimilitud" id="toc-prueba-de-razón-de-verosimilitud" class="nav-link" data-scroll-target="#prueba-de-razón-de-verosimilitud">Prueba de razón de verosimilitud</a></li>
  <li><a href="#interpretación-odds-ratio" id="toc-interpretación-odds-ratio" class="nav-link" data-scroll-target="#interpretación-odds-ratio">Interpretación: odds ratio</a></li>
  <li><a href="#probabilidades-predichas" id="toc-probabilidades-predichas" class="nav-link" data-scroll-target="#probabilidades-predichas">Probabilidades predichas</a></li>
  </ul></li>
  <li><a href="#sec-poisson" id="toc-sec-poisson" class="nav-link" data-scroll-target="#sec-poisson">Parte 2 — GLM Poisson: langosta espinosa y densidad de pasto</a>
  <ul class="collapse">
  <li><a href="#interpretación-razón-de-tasas" id="toc-interpretación-razón-de-tasas" class="nav-link" data-scroll-target="#interpretación-razón-de-tasas">Interpretación: razón de tasas</a></li>
  <li><a href="#verificación-de-la-equidispersión" id="toc-verificación-de-la-equidispersión" class="nav-link" data-scroll-target="#verificación-de-la-equidispersión">Verificación de la equidispersión</a></li>
  </ul></li>
  <li><a href="#sec-sobredispersion" id="toc-sec-sobredispersion" class="nav-link" data-scroll-target="#sec-sobredispersion">Parte 3 — Conteos entre sitios y épocas: sobredispersión</a>
  <ul class="collapse">
  <li><a href="#paso-1-explorar-media-y-varianza-por-grupo" id="toc-paso-1-explorar-media-y-varianza-por-grupo" class="nav-link" data-scroll-target="#paso-1-explorar-media-y-varianza-por-grupo">Paso 1 — Explorar: media y varianza por grupo</a></li>
  <li><a href="#paso-2-ajustar-el-poisson-e-inspeccionar-φ" id="toc-paso-2-ajustar-el-poisson-e-inspeccionar-φ" class="nav-link" data-scroll-target="#paso-2-ajustar-el-poisson-e-inspeccionar-φ">Paso 2 — Ajustar el Poisson e inspeccionar φ</a></li>
  <li><a href="#paso-3-corregir-con-la-binomial-negativa" id="toc-paso-3-corregir-con-la-binomial-negativa" class="nav-link" data-scroll-target="#paso-3-corregir-con-la-binomial-negativa">Paso 3 — Corregir con la binomial negativa</a></li>
  <li><a href="#paso-4-hay-diferencias-entre-zonas-y-épocas" id="toc-paso-4-hay-diferencias-entre-zonas-y-épocas" class="nav-link" data-scroll-target="#paso-4-hay-diferencias-entre-zonas-y-épocas">Paso 4 — ¿Hay diferencias entre zonas y épocas?</a></li>
  <li><a href="#paso-5-interpretar-razones-de-tasas" id="toc-paso-5-interpretar-razones-de-tasas" class="nav-link" data-scroll-target="#paso-5-interpretar-razones-de-tasas">Paso 5 — Interpretar: razones de tasas</a></li>
  </ul></li>
  <li><a href="#sec-checklist" id="toc-sec-checklist" class="nav-link" data-scroll-target="#sec-checklist">Parte 4 — Lista de verificación antes de reportar el GLM</a></li>
  <li><a href="#cierre-una-base-para-el-futuro-proyecto-de-grado" id="toc-cierre-una-base-para-el-futuro-proyecto-de-grado" class="nav-link" data-scroll-target="#cierre-una-base-para-el-futuro-proyecto-de-grado">Cierre — Una base para el futuro proyecto de grado</a>
  <ul class="collapse">
  <li><a href="#actividad-en-clase-10-minutos-sin-código" id="toc-actividad-en-clase-10-minutos-sin-código" class="nav-link" data-scroll-target="#actividad-en-clase-10-minutos-sin-código">Actividad en clase (10 minutos, sin código)</a></li>
  <li><a href="#antes-de-la-próxima-sesión-tarea-corta" id="toc-antes-de-la-próxima-sesión-tarea-corta" class="nav-link" data-scroll-target="#antes-de-la-próxima-sesión-tarea-corta">Antes de la próxima sesión (tarea corta)</a></li>
  </ul></li>
  <li><a href="#sec-apoyo" id="toc-sec-apoyo" class="nav-link" data-scroll-target="#sec-apoyo">Material de apoyo</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/portada_glm.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:85.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<section id="materiales-requeridos-para-el-taller-en-clase" class="level2 titulo-seccion">
<h2 class="titulo-seccion anchored" data-anchor-id="materiales-requeridos-para-el-taller-en-clase">Materiales requeridos para el taller en clase</h2>
<p>En los siguientes enlaces se podrán descargar archivos comprimidos de los talleres donde se pueden aplicar procedimientos para los modelos de regresión lineal generalizada - GLM, con datos simulados en ecosistemas del Caribe colombiano (📰 Taller 4. Regresión lineal generalizada).</p>
<div class="material-apoyo">
<ul>
<li><i class="bi bi-file-earmark-zip"></i> <a href="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_clase/taller4_clase.zip">Taller 4. Regresión lineal generalizada</a></li>
</ul>
</div>
<p><strong>Nota:</strong> una vez se descarguen los materiales, se requiere descomprimirlos antes de realizar cualquier procedimiento y seguir las orientaciones del docente para realizar los ejercicios requeridos.</p>
<section id="diapositivas-en-vivo---slides.com" class="level3">
<h3 class="anchored" data-anchor-id="diapositivas-en-vivo---slides.com">Diapositivas en vivo - Slides.com</h3>
<p><img src="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/figuras/slides.com.jpg" class="img-fluid" width="110"></p>
<div class="material-apoyo">
<ul>
<li><i class="bi bi-easel"></i> <a href="https://slides.com/d/rrKfVpI/live">Diapositivas del Taller 4. GLM</a></li>
</ul>
</div>
</section>
</section>
<section id="objetivos-del-taller" class="level2">
<h2 class="anchored" data-anchor-id="objetivos-del-taller">Objetivos del taller</h2>
<p>Este taller acompaña la sesión de diapositivas <em>“Modelos Lineales Generalizados (GLM)”</em> (RA1, RA2) del sábado en la tarde de la Semana 2. Al terminar, se podrá:</p>
<ul>
<li>Elegir la familia adecuada según el tipo de variable respuesta.</li>
<li>Ajustar e interpretar un <strong>GLM binomial</strong> (enlace logit, odds ratio, prueba de razón de verosimilitud).</li>
<li>Ajustar e interpretar un <strong>GLM Poisson</strong> (enlace log, razón de tasas).</li>
<li>Comparar conteos <strong>entre sitios y épocas</strong>, diagnosticar <strong>sobredispersión</strong> (φ) y corregirla con la <strong>binomial negativa</strong>.</li>
</ul>
<p>Se usan los mismos tres ejemplos de las diapositivas, con las mismas semillas, de modo que los resultados coinciden con los que aparecen en ellas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Núcleo y material complementario
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este taller cubre lo esencial para la sesión. Los temas que amplían el análisis (proporciones, centrado de predictores, intervalos construidos a mano, cuasi-Poisson en detalle, comparaciones por pares, offset y el estudio de caso de la tortuga caguama) están en el <a href="#sec-apoyo">Material complementario</a>, para consultarlos cuando el propio proyecto los requiera.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los datos siguen siendo <strong>simulados</strong> con <code>set.seed()</code> fijando la semilla en cada sección. Construidos para ilustrar cada modelo con claridad, no para representar mediciones reales.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Librerías requeridas</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># La binomial negativa se ajusta con MASS::glm.nb(). Se llama con el prefijo</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># MASS:: para no cargar el paquete, que enmascara dplyr::select()</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="sec-fundamentos" class="level2">
<h2 class="anchored" data-anchor-id="sec-fundamentos">Antes de empezar: ¿qué es un GLM?</h2>
<p>Un Modelo Lineal Generalizado tiene tres componentes:</p>
<ol type="1">
<li><strong>Componente aleatorio</strong>: la distribución de la variable respuesta dentro de la familia exponencial. La varianza queda ligada a la media: binomial Var = np(1 − p); Poisson Var = μ.</li>
<li><strong>Componente sistemático</strong>: el predictor lineal <span class="math inline">\(\eta = \beta_0 + \beta_1X_1 + \dots\)</span>, igual que en <code>lm()</code>.</li>
<li><strong>Función de enlace</strong> <span class="math inline">\(g(\mu)\)</span>: conecta la media esperada con el predictor lineal, <span class="math inline">\(\eta = g(\mu)\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>No es lo mismo que transformar Y
</div>
</div>
<div class="callout-body-container callout-body">
<p>Transformar <code>log(Y)</code> antes de un <code>lm()</code> altera cada observación y falla con los ceros (log 0 = −∞), lo que obliga a recursos como <code>log(Y + 1)</code>. En un GLM, la función de enlace actúa sobre el <strong>valor esperado</strong> <span class="math inline">\(\mu\)</span> y no sobre los datos: la varianza se modela en su escala real.</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo de variable respuesta</th>
<th>Familia</th>
<th>Enlace</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continua, aprox. normal</td>
<td>Gaussiana</td>
<td>Identidad</td>
<td>Longitud corporal de un pez</td>
</tr>
<tr class="even">
<td>Binaria (0/1) o proporción</td>
<td>Binomial</td>
<td>Logit</td>
<td>Presencia/ausencia, supervivencia</td>
</tr>
<tr class="odd">
<td>Conteo (0, 1, 2, …)</td>
<td>Poisson</td>
<td>Log</td>
<td>Individuos por cuadrante</td>
</tr>
<tr class="even">
<td>Conteo sobredisperso</td>
<td>Binomial negativa</td>
<td>Log</td>
<td>Peces loro por transecto (cardúmenes)</td>
</tr>
</tbody>
</table>
<p>Las proporciones (p.&nbsp;ej., juveniles vivos de un total por tanque) también se modelan con la familia binomial; la forma de hacerlo está en el material complementario.</p>
<p>Se define desde ya una función para el parámetro de dispersión, que se usará en las Partes 2 y 3:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># φ = suma de residuos de Pearson al cuadrado / g.l. residuales</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>phi <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo, <span class="at">type =</span> <span class="st">"pearson"</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> modelo<span class="sc">$</span>df.residual</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="sec-binomial" class="level2">
<h2 class="anchored" data-anchor-id="sec-binomial">Parte 1 — GLM binomial: enfermedad de coral y temperatura</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/1_glm_parte1_binomial.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p><strong>Pregunta:</strong> ¿Aumenta con la temperatura la <strong>probabilidad</strong> de que una colonia de coral presente signos de <strong>enfermedad de banda negra</strong>?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">365</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de colonias</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">80</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperatura del agua (°C)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>temperatura <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="dv">27</span>, <span class="fl">31.5</span>), <span class="dv">2</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Presencia (1) o ausencia (0) de la enfermedad</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>enfermo <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">14.5</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> temperatura))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>coral_enf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">colonia =</span> <span class="fu">paste0</span>(<span class="st">"C"</span>, <span class="dv">1</span><span class="sc">:</span>n), temperatura, enfermo)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coral_enf, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> colonia </th>
   <th style="text-align:right;font-weight: bold;"> temperatura </th>
   <th style="text-align:right;font-weight: bold;"> enfermo </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> C1 </td>
   <td style="text-align:right;"> 30.60 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C2 </td>
   <td style="text-align:right;"> 27.42 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C3 </td>
   <td style="text-align:right;"> 28.04 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C4 </td>
   <td style="text-align:right;"> 27.15 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C5 </td>
   <td style="text-align:right;"> 29.20 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C6 </td>
   <td style="text-align:right;"> 29.14 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C7 </td>
   <td style="text-align:right;"> 29.39 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C8 </td>
   <td style="text-align:right;"> 31.09 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C9 </td>
   <td style="text-align:right;"> 30.25 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> C10 </td>
   <td style="text-align:right;"> 30.02 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Colonias sanas (0) y enfermas (1)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coral_enf<span class="sc">$</span>enfermo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 0  1 
43 37 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM binomial</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mod_enf <span class="ot">&lt;-</span> <span class="fu">glm</span>(enfermo <span class="sc">~</span> temperatura, <span class="at">data =</span> coral_enf, <span class="at">family =</span> binomial)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Consultar resultados</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_enf)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = enfermo ~ temperatura, family = binomial, data = coral_enf)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -14.7714     5.1927  -2.845  0.00445 **
temperatura   0.5012     0.1777   2.821  0.00479 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 110.45  on 79  degrees of freedom
Residual deviance: 101.76  on 78  degrees of freedom
AIC: 105.76

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>La columna <code>z value</code> es la <strong>prueba de Wald</strong>: z = b₁ / EE. En un GLM se usa z y no t, porque la varianza la fija la familia (binomial o Poisson) en lugar de estimarse aparte.</p>
<section id="prueba-de-razón-de-verosimilitud" class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-razón-de-verosimilitud">Prueba de razón de verosimilitud</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar la devianza con y sin temperatura</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_enf, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: enfermo

Terms added sequentially (first to last)

            Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)   
NULL                           79     110.45            
temperatura  1   8.6931        78     101.76 0.003194 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Compara la devianza del modelo nulo con la del modelo con temperatura. Es la prueba preferida para decidir si un predictor aporta, sobre todo con muestras pequeñas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proporción de la devianza explicada (análogo aproximado al r²)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> mod_enf<span class="sc">$</span>deviance <span class="sc">/</span> mod_enf<span class="sc">$</span>null.deviance</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07870429</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Significativo no es lo mismo que explicativo
</div>
</div>
<div class="callout-body-container callout-body">
<p>La temperatura reduce la devianza solo un 7.9 %. El efecto es real, pero otros factores (especie hospedera, sedimentación, patógenos) explican la mayor parte de la variación.</p>
</div>
</div>
</section>
<section id="interpretación-odds-ratio" class="level3">
<h3 class="anchored" data-anchor-id="interpretación-odds-ratio">Interpretación: odds ratio</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OR = exp(b) con su IC 95 %</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(mod_enf), <span class="fu">confint</span>(mod_enf)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      OR        2.5 %      97.5 %
(Intercept) 3.844595e-07 9.039334e-12 0.007247974
temperatura 1.650694e+00 1.178433e+00 2.376990861</code></pre>
</div>
</div>
<p>Por cada +1 °C, los odds de que la colonia esté enferma se multiplican por 1.65 (IC 95 %: 1.18–2.38). Como el IC del OR no incluye 1, la asociación es estadísticamente significativa.</p>
<p>El OR del intercepto es prácticamente 0 porque corresponde a una temperatura de 0 °C, que no tiene sentido biológico. No afecta la interpretación de la temperatura (en el material complementario se muestra cómo volverlo interpretable centrando el predictor).</p>
</section>
<section id="probabilidades-predichas" class="level3">
<h3 class="anchored" data-anchor-id="probabilidades-predichas">Probabilidades predichas</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperaturas de interés</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">temperatura =</span> <span class="dv">28</span><span class="sc">:</span><span class="dv">31</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidad predicha en la escala de respuesta</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(nd, <span class="at">prob =</span> <span class="fu">round</span>(<span class="fu">predict</span>(mod_enf, <span class="at">newdata =</span> nd, <span class="at">type =</span> <span class="st">"response"</span>), <span class="dv">3</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  temperatura  prob
1          28 0.323
2          29 0.441
3          30 0.566
4          31 0.683</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>predict(..., type = "response")</code> devuelve la probabilidad (0 a 1). Sin <code>type = "response"</code> se obtiene el predictor lineal en escala logit.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construir gráfico</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coral_enf, <span class="fu">aes</span>(<span class="at">x =</span> temperatura, <span class="at">y =</span> enfermo)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.03</span>, <span class="at">width =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"grey55"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> binomial),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"navy"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span>   <span class="co"># Curva logística e IC 95 %</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Etiquetas de ejes</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Temperatura (°C)"</span>, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probabilidad de banda negra"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar tema</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller4_GLM_Binomial_Poisson_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p><code>geom_smooth()</code> ajusta el mismo GLM binomial y dibuja la curva con su IC 95 %, que nunca sale de [0, 1].</p>
<p><strong>Para discutir:</strong> el OR es constante (1.65 por °C), pero la probabilidad predicha sube 12 puntos entre 28 y 29 °C y 12 entre 30 y 31 °C, y subiría menos en los extremos de la curva. ¿Por qué un OR constante no implica un aumento constante de la probabilidad?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Cómo reportar el resultado
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la sección de resultados de un artículo o de la tesis, se reportan el efecto en escala interpretable (OR) con su IC, la prueba de razón de verosimilitud y la devianza explicada. Por ejemplo:</p>
<blockquote class="blockquote">
<p>La probabilidad de presentar banda negra aumentó con la temperatura del agua (GLM binomial, enlace logit; OR = 1,65 por °C; IC 95 %: 1,18–2,38; χ²<sub>1</sub> = 8,69; p = 0,003), aunque la temperatura explicó solo el 7,9 % de la devianza.</p>
</blockquote>
<p>Esta estructura es la que se espera en la Evidencia 2.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Diseño (RA1)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si varias colonias provienen del mismo arrecife y comparten la misma temperatura, no son réplicas independientes para el efecto de la temperatura. En ese caso la unidad de análisis sería el arrecife o se requeriría un modelo mixto (fuera del alcance de esta sesión).</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-poisson" class="level2">
<h2 class="anchored" data-anchor-id="sec-poisson">Parte 2 — GLM Poisson: langosta espinosa y densidad de pasto</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/2_glm_parte2_poisson.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p><strong>Pregunta:</strong> ¿Aumenta el <strong>número de juveniles</strong> de <em>Panulirus argus</em> por parche de pastos marinos con la <strong>densidad del pasto</strong>?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">28</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de parches</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">32</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Índice de densidad de pasto (1–10)</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>densidad_pasto <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n2, <span class="dv">1</span>, <span class="dv">10</span>), <span class="dv">1</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo de juveniles por parche</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>juveniles <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n2, <span class="fu">exp</span>(<span class="fl">0.9</span> <span class="sc">+</span> <span class="fl">0.15</span> <span class="sc">*</span> densidad_pasto))</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>langosta <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">parche =</span> <span class="fu">paste0</span>(<span class="st">"L"</span>, <span class="dv">1</span><span class="sc">:</span>n2), densidad_pasto, juveniles)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(langosta, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> parche </th>
   <th style="text-align:right;font-weight: bold;"> densidad_pasto </th>
   <th style="text-align:right;font-weight: bold;"> juveniles </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> L1 </td>
   <td style="text-align:right;"> 1.3 </td>
   <td style="text-align:right;"> 5 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L2 </td>
   <td style="text-align:right;"> 1.8 </td>
   <td style="text-align:right;"> 5 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L3 </td>
   <td style="text-align:right;"> 5.3 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L4 </td>
   <td style="text-align:right;"> 9.0 </td>
   <td style="text-align:right;"> 13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L5 </td>
   <td style="text-align:right;"> 1.8 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L6 </td>
   <td style="text-align:right;"> 7.8 </td>
   <td style="text-align:right;"> 7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L7 </td>
   <td style="text-align:right;"> 1.3 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L8 </td>
   <td style="text-align:right;"> 8.8 </td>
   <td style="text-align:right;"> 8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L9 </td>
   <td style="text-align:right;"> 6.1 </td>
   <td style="text-align:right;"> 6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L10 </td>
   <td style="text-align:right;"> 9.5 </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM Poisson</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mod_lang <span class="ot">&lt;-</span> <span class="fu">glm</span>(juveniles <span class="sc">~</span> densidad_pasto, <span class="at">data =</span> langosta, <span class="at">family =</span> poisson)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Consultar resultados</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_lang)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = juveniles ~ densidad_pasto, family = poisson, data = langosta)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     0.83159    0.19913   4.176 2.96e-05 ***
densidad_pasto  0.15040    0.02893   5.198 2.02e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 59.598  on 31  degrees of freedom
Residual deviance: 31.405  on 30  degrees of freedom
AIC: 144.07

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="interpretación-razón-de-tasas" class="level3">
<h3 class="anchored" data-anchor-id="interpretación-razón-de-tasas">Interpretación: razón de tasas</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Razón de tasas del predictor</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_lang)[<span class="st">"densidad_pasto"</span>])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>densidad_pasto 
      1.162295 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IC 95 % en escala exp()</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(mod_lang))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
(Intercept)    1.533645 3.350367
densidad_pasto 1.098824 1.230965</code></pre>
</div>
</div>
<p>Por cada unidad adicional del índice de densidad de pasto, la abundancia esperada de juveniles se multiplica por 1.16. Esta cantidad, exp(β), es la <strong>razón de tasas</strong> del predictor.</p>
</section>
<section id="verificación-de-la-equidispersión" class="level3">
<h3 class="anchored" data-anchor-id="verificación-de-la-equidispersión">Verificación de la equidispersión</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_lang)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.005818</code></pre>
</div>
</div>
<p>φ ≈ 1.01: muy cerca de 1. Este Poisson, sin corrección adicional, es adecuado para estos datos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si las unidades de muestreo difieren en área, tiempo o esfuerzo (parches de distinto tamaño, nasas caladas distinto número de horas), el modelo debe incluir un <strong>offset</strong>. Se explica en el material complementario.</p>
</div>
</div>
<p><strong>Para discutir:</strong> los juveniles de langosta suelen refugiarse en grupos bajo una misma estructura. Si eso ocurriera en estos parches, ¿qué se esperaría que pasara con φ? ¿Qué consecuencia tendría sobre los valores p del Poisson?</p>
<hr>
</section>
</section>
<section id="sec-sobredispersion" class="level2">
<h2 class="anchored" data-anchor-id="sec-sobredispersion">Parte 3 — Conteos entre sitios y épocas: sobredispersión</h2>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="figuras_portadas/3_glm_parte3_sobredispersion.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:80.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<p><strong>Pregunta:</strong> ¿Difiere la <strong>abundancia del pez loro rayado</strong> (<em>Scarus iseri</em>) entre zonas con distinto nivel de uso y entre épocas climáticas?</p>
<p>Este es el caso más común en monitoreos ecológicos: un <strong>conteo</strong> y uno o dos <strong>factores</strong> (sitio, zona, época). Es el equivalente de un ANOVA de dos vías, pero para conteos. En cada zona (uso intensivo, intermedia y protegida) y en cada época (seca y lluviosa) se censaron 8 transectos ubicados al azar: 48 transectos en total.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">147</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Zona de uso (3 niveles; "Uso intensivo" es el nivel de referencia)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>zona <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Uso intensivo"</span>, <span class="st">"Intermedia"</span>, <span class="st">"Protegida"</span>), <span class="at">each =</span> <span class="dv">16</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Uso intensivo"</span>, <span class="st">"Intermedia"</span>, <span class="st">"Protegida"</span>))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Época climática (2 niveles; "Seca" es el nivel de referencia)</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>epoca <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Seca"</span>, <span class="st">"Lluviosa"</span>), <span class="at">each =</span> <span class="dv">8</span>), <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Seca"</span>, <span class="st">"Lluviosa"</span>))</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Abundancia esperada por zona y época</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">1.3</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.45</span>, <span class="fl">0.95</span>)[<span class="fu">as.integer</span>(zona)] <span class="sc">-</span> <span class="fl">0.35</span> <span class="sc">*</span> (epoca <span class="sc">==</span> <span class="st">"Lluviosa"</span>))</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteos agregados (binomial negativa)</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>abundancia <span class="ot">&lt;-</span> <span class="fu">rnbinom</span>(<span class="dv">48</span>, <span class="at">mu =</span> mu, <span class="at">size =</span> <span class="fl">2.5</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>loro <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">transecto =</span> <span class="fu">paste0</span>(<span class="st">"T"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">48</span>), zona, epoca, abundancia)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(loro, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> transecto </th>
   <th style="text-align:left;font-weight: bold;"> zona </th>
   <th style="text-align:left;font-weight: bold;"> epoca </th>
   <th style="text-align:right;font-weight: bold;"> abundancia </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> T1 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T2 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T3 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 5 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T4 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T5 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T6 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T7 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T8 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T9 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Lluviosa </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T10 </td>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Lluviosa </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="paso-1-explorar-media-y-varianza-por-grupo" class="level3">
<h3 class="anchored" data-anchor-id="paso-1-explorar-media-y-varianza-por-grupo">Paso 1 — Explorar: media y varianza por grupo</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Media y varianza de la abundancia en cada combinación de zona y época</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>loro <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(zona, epoca) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(abundancia), <span class="dv">1</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">varianza =</span> <span class="fu">round</span>(<span class="fu">var</span>(abundancia), <span class="dv">1</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> zona </th>
   <th style="text-align:left;font-weight: bold;"> epoca </th>
   <th style="text-align:right;font-weight: bold;"> media </th>
   <th style="text-align:right;font-weight: bold;"> varianza </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 3.9 </td>
   <td style="text-align:right;"> 4.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Uso intensivo </td>
   <td style="text-align:left;"> Lluviosa </td>
   <td style="text-align:right;"> 1.8 </td>
   <td style="text-align:right;"> 2.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Intermedia </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 4.2 </td>
   <td style="text-align:right;"> 6.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Intermedia </td>
   <td style="text-align:left;"> Lluviosa </td>
   <td style="text-align:right;"> 3.5 </td>
   <td style="text-align:right;"> 9.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Protegida </td>
   <td style="text-align:left;"> Seca </td>
   <td style="text-align:right;"> 10.4 </td>
   <td style="text-align:right;"> 119.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Protegida </td>
   <td style="text-align:left;"> Lluviosa </td>
   <td style="text-align:right;"> 6.5 </td>
   <td style="text-align:right;"> 14.3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Abundancia por zona y época</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loro, <span class="fu">aes</span>(<span class="at">x =</span> zona, <span class="at">y =</span> abundancia, <span class="at">fill =</span> epoca)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Zona"</span>, <span class="at">y =</span> <span class="st">"Peces loro por transecto"</span>, <span class="at">fill =</span> <span class="st">"Época"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Taller4_GLM_Binomial_Poisson_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>En un Poisson, la varianza debería parecerse a la media. Aquí, en varios grupos, la varianza es bastante mayor que la media: es la primera señal de <strong>sobredispersión</strong>, típica de peces que se mueven en grupos.</p>
</section>
<section id="paso-2-ajustar-el-poisson-e-inspeccionar-φ" class="level3">
<h3 class="anchored" data-anchor-id="paso-2-ajustar-el-poisson-e-inspeccionar-φ">Paso 2 — Ajustar el Poisson e inspeccionar φ</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM Poisson con zona, época y su interacción</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>mod_loro_p <span class="ot">&lt;-</span> <span class="fu">glm</span>(abundancia <span class="sc">~</span> zona <span class="sc">*</span> epoca, <span class="at">data =</span> loro, <span class="at">family =</span> poisson)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_loro_p)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.383721</code></pre>
</div>
</div>
<p>φ ≈ 3.38, claramente mayor que 1: hay <strong>sobredispersión</strong>. Si se reportara este Poisson, los errores estándar quedarían subestimados y los valores p exagerarían la evidencia.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Desde qué valor de φ hay que preocuparse?
</div>
</div>
<div class="callout-body-container callout-body">
<p>No hay un corte único. Valores cercanos a 1 son compatibles con el Poisson; muchos autores usan 1,2–1,5 como <strong>regla práctica</strong> para empezar a revisar, y valores como 2 o más indican una sobredispersión que no conviene ignorar. Más que el umbral, importa si la corrección cambia las conclusiones.</p>
</div>
</div>
</section>
<section id="paso-3-corregir-con-la-binomial-negativa" class="level3">
<h3 class="anchored" data-anchor-id="paso-3-corregir-con-la-binomial-negativa">Paso 3 — Corregir con la binomial negativa</h3>
<p>La binomial negativa supone Var = μ + μ²/θ: añade un parámetro θ que absorbe la agregación (a menor θ, mayor agregación). Se ajusta con <code>MASS::glm.nb()</code> y la misma fórmula:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar binomial negativa</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>mod_loro_nb <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(abundancia <span class="sc">~</span> zona <span class="sc">*</span> epoca, <span class="at">data =</span> loro)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_loro_nb)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.030305</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar los dos modelos</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">modelo =</span> <span class="fu">c</span>(<span class="st">"Poisson"</span>, <span class="st">"Binomial negativa"</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">phi =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">phi</span>(mod_loro_p), <span class="fu">phi</span>(mod_loro_nb)), <span class="dv">2</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(mod_loro_p), <span class="fu">AIC</span>(mod_loro_nb)), <span class="dv">1</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> modelo </th>
   <th style="text-align:right;font-weight: bold;"> phi </th>
   <th style="text-align:right;font-weight: bold;"> AIC </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Poisson </td>
   <td style="text-align:right;"> 3.38 </td>
   <td style="text-align:right;"> 295.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Binomial negativa </td>
   <td style="text-align:right;"> 1.03 </td>
   <td style="text-align:right;"> 252.8 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Con la binomial negativa, φ queda cerca de 1 y el AIC baja de 295.1 a 252.8: es el modelo adecuado para estos datos. Otra alternativa es el <strong>cuasi-Poisson</strong> (<code>family = quasipoisson</code>), que corrige los errores estándar pero no permite calcular AIC; se compara con la binomial negativa en el material complementario.</p>
</section>
<section id="paso-4-hay-diferencias-entre-zonas-y-épocas" class="level3">
<h3 class="anchored" data-anchor-id="paso-4-hay-diferencias-entre-zonas-y-épocas">Paso 4 — ¿Hay diferencias entre zonas y épocas?</h3>
<p>Como en un ANOVA, primero se revisa la interacción con la <strong>prueba de razón de verosimilitud</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de razón de verosimilitud para cada término</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_loro_nb, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: Negative Binomial(2.8202), link: log

Response: abundancia

Terms added sequentially (first to last)

           Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                          47     79.443              
zona        2  19.0481        45     60.395 7.307e-05 ***
epoca       1   4.3762        44     56.019   0.03644 *  
zona:epoca  2   1.0481        42     54.971   0.59211    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>La interacción no es significativa (p = 0.59): la diferencia entre zonas es similar en las dos épocas. Se ajusta entonces el modelo aditivo, más sencillo, y se prueba cada factor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo aditivo: zona + época</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>mod_loro <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(abundancia <span class="sc">~</span> zona <span class="sc">+</span> epoca, <span class="at">data =</span> loro)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de razón de verosimilitud para cada factor</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_loro, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: Negative Binomial(2.73), link: log

Response: abundancia

Terms added sequentially (first to last)

      Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                     47     78.074              
zona   2  18.6535        45     59.420 8.901e-05 ***
epoca  1   4.2923        44     55.128   0.03829 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Se usa esta prueba, y no los valores p de <code>summary()</code>, porque la zona tiene tres niveles: la prueba evalúa el factor completo (χ² con 2 g.l.), mientras que cada coeficiente de <code>summary()</code> solo compara una zona con la de referencia.</p>
</section>
<section id="paso-5-interpretar-razones-de-tasas" class="level3">
<h3 class="anchored" data-anchor-id="paso-5-interpretar-razones-de-tasas">Paso 5 — Interpretar: razones de tasas</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Razones de tasas e IC 95 %</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">RT =</span> <span class="fu">coef</span>(mod_loro), <span class="fu">confint</span>(mod_loro)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      RT     2.5 %    97.5 %
(Intercept)    3.3950214 2.1548614 5.3724254
zonaIntermedia 1.4283048 0.8058426 2.5429398
zonaProtegida  3.0533003 1.7805870 5.2780000
epocaLluviosa  0.6276598 0.4029492 0.9751767</code></pre>
</div>
</div>
<p>Con factores, cada razón de tasas compara un nivel con el <strong>nivel de referencia</strong> (uso intensivo para la zona, época seca para la época):</p>
<ul>
<li>En la zona <strong>protegida</strong>, la abundancia esperada es 3.05 veces la de la zona de uso intensivo (IC 95 %: 1.78–5.28).</li>
<li>La zona <strong>intermedia</strong> no difiere con claridad de la de uso intensivo: su IC (0.81–2.54) incluye 1.</li>
<li>En la época <strong>lluviosa</strong>, la abundancia esperada es 0.63 veces la de la época seca, es decir, un 37 % menor.</li>
</ul>
<p>La comparación entre la zona intermedia y la protegida no aparece en esta tabla; las <strong>comparaciones por pares</strong> entre todas las zonas están en el material complementario.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Cómo reportar el resultado
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>La abundancia de <em>S. iseri</em> difirió entre zonas (GLM binomial negativa, enlace log; χ²<sub>2</sub> = 18,7; p &lt; 0,001) y entre épocas (χ²<sub>1</sub> = 4,3; p = 0,038), sin interacción entre ambos factores. En la zona protegida, la abundancia esperada fue 3,1 veces la de la zona de uso intensivo (IC 95 %: 1,8–5,3). Se descartó el modelo Poisson por sobredispersión (φ = 3,4; ΔAIC = 42,3).</p>
</blockquote>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Del GLM a PERMANOVA (Semana 4)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este GLM responde la pregunta <strong>especie por especie</strong>: ¿cambia la abundancia del pez loro entre zonas y épocas? Si la pregunta es si cambia la <strong>comunidad completa</strong> (todas las especies a la vez), se necesita un análisis multivariado como PERMANOVA o ANOSIM, que se trabaja en la Semana 4. En un estudio de diversidad, ambos enfoques se complementan: el multivariado muestra si la comunidad difiere y el GLM muestra qué especies explican esa diferencia.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-checklist" class="level2">
<h2 class="anchored" data-anchor-id="sec-checklist">Parte 4 — Lista de verificación antes de reportar el GLM</h2>
<p>Antes de reportar cualquier GLM, conviene verificar:</p>
<ul>
<li>¿Se eligió la familia según el tipo real de la variable respuesta?</li>
<li>¿Se reportaron los efectos en escala interpretable (OR o razón de tasas) con su IC 95 %?</li>
<li>¿Se evaluó el efecto con la prueba de razón de verosimilitud (<code>anova(..., test = "Chisq")</code>), sobre todo si el predictor es un factor con más de dos niveles?</li>
<li>En los modelos de conteo, ¿se calculó φ? Si es claramente mayor que 1, ¿se corrigió con binomial negativa (o cuasi-Poisson)?</li>
<li>Si las unidades de muestreo difieren en área, tiempo o esfuerzo, ¿se incluyó un offset? (ver material complementario)</li>
<li>¿Se evitó extrapolar fuera del rango observado de los predictores?</li>
</ul>
<hr>
</section>
<section id="cierre-una-base-para-el-futuro-proyecto-de-grado" class="level2">
<h2 class="anchored" data-anchor-id="cierre-una-base-para-el-futuro-proyecto-de-grado">Cierre — Una base para el futuro proyecto de grado</h2>
<section id="actividad-en-clase-10-minutos-sin-código" class="level3">
<h3 class="anchored" data-anchor-id="actividad-en-clase-10-minutos-sin-código">Actividad en clase (10 minutos, sin código)</h3>
<p>En parejas, se responde sobre el proyecto de grado de cada integrante:</p>
<ol type="1">
<li>¿La variable de interés es presencia/ausencia, una proporción o un conteo?</li>
<li>Según eso, ¿qué familia y qué función de enlace corresponden?</li>
<li>¿Qué predictores se incluirían (continuos como temperatura o profundidad, o factores como sitio y época), y con qué justificación?</li>
<li>Si es un conteo, ¿se esperaría sobredispersión (agregación, parches, exceso de ceros)?</li>
</ol>
<p>Luego, se escribe la ecuación del GLM en palabras: “la probabilidad / el conteo de ___ depende de ___, y se espera que [aumente/disminuya] porque ___”.</p>
</section>
<section id="antes-de-la-próxima-sesión-tarea-corta" class="level3">
<h3 class="anchored" data-anchor-id="antes-de-la-próxima-sesión-tarea-corta">Antes de la próxima sesión (tarea corta)</h3>
<p>Se puede adaptar el código de este taller a la propia idea, con <strong>valores simulados pero plausibles</strong> para el sistema de estudio:</p>
<ol type="1">
<li>Se copia la sección más parecida a la variable propia (binaria → <a href="#sec-binomial">Parte 1</a>; conteo con un predictor continuo → <a href="#sec-poisson">Parte 2</a>; conteo entre sitios o épocas → <a href="#sec-sobredispersion">Parte 3</a>).</li>
<li>Se cambian los nombres de las variables y los coeficientes simulados por los esperados en el propio tema.</li>
<li>Se ejecutan <code>anova(..., test = "Chisq")</code> y <code>phi()</code> sobre el modelo, y se revisa la lista de verificación (<a href="#sec-checklist">Parte 4</a>). ¿La salida de R es coherente con lo planteado?</li>
</ol>
<p>Con esto se cierran las Evidencias 1 y 2 (inferencia, regresión y GLM) y se completa el flujo: elegir familia → ajustar → interpretar en escala exp() → diagnosticar → comparar modelos.</p>
<hr>
</section>
</section>
<section id="sec-apoyo" class="level2">
<h2 class="anchored" data-anchor-id="sec-apoyo">Material de apoyo</h2>
<p><img src="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/html/figuras_portadas/3_hipotesis/9_material_apoyo.jpg" class="img-fluid" width="146"></p>
<p>Para repasar y profundizar después de la sesión:</p>
<div class="material-apoyo">
<ul>
<li><i class="bi bi-ui-checks"></i> <a href="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Cuestionario1_GLM.html"><strong>Cuestionario 1 · GLM binomial y Poisson</strong></a> — 12 preguntas de opción múltiple con pista y explicación, basadas en las Partes 1 a 4 de este taller.</li>
<li><i class="bi bi-ui-checks"></i> <a href="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Cuestionario2_GLM.html"><strong>Cuestionario 2 · GLM binomial y Poisson</strong></a> — escenarios nuevos con preguntas abiertas para interpretar salidas de modelos, con retroalimentación al final.</li>
<li><i class="bi bi-journal-text"></i> <a href="https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Complemento_Taller4.html"><strong>Material complementario · Cuando el GLM se complica</strong></a> — proporciones, centrado de predictores, intervalos en escala logit, sobredispersión a fondo (cuasi-Poisson y binomial negativa), comparaciones por pares entre sitios, offset y el estudio de caso de nidos de tortuga caguama.</li>
</ul>
</div>
<hr>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<ul>
<li><p>Quinn, G. P., &amp; Keough, M. J. (2024). <em>Experimental Design and Data Analysis for Biologists</em> (2nd ed.). Cambridge University Press. <a href="https://mjkeough.github.io/examples.html">enlace_ejercicios</a></p></li>
<li><p>Logan, M. (2011). <em>Biostatistical Design and Analysis Using R</em>. Wiley-Blackwell. <a href="https://bcs.wiley.com/he-bcs/Books?action=index&amp;bcsId=5684&amp;itemId=1405190086">enlace_ejercicios</a>; <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781444319620">enlace_libro</a></p></li>
<li><p>Calvo Sendín, J. F. (2025). <em>Análisis estadístico de datos biológicos en R</em>. Universidad de Murcia. — Referencia técnica para GLM binomial/Poisson y sobredispersión. <a href="https://webs.um.es/jfcalvo/aedbr.html?utm_source=acortador&amp;utm_medium=referral&amp;utm_campaign=acortador_url&amp;utm_id=aedbr">enlace</a></p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los ejemplos y bases de datos de este taller son de elaboración propia para este curso; no reproducen los ejercicios ni el código de las fuentes citadas.</p>
</div>
</div>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Taller · GLM Binomial y Poisson en R"</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Bioestadística · Semana 2 · 2026-II"</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> </span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co">  name: Nombre del Estudiante</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co">  url: https://www.unimagdalena.edu.co/</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co">  afiliation: Grupo de Investigación</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co">  afiliation-url: https://</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner:</span><span class="co"> "#2098D9"</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true    # Tabla de contenido</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: Menú flotante</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true     # Opción para descargar los códigos</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: false      # Visualización de los códigos en el reporte</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co">    css: ["styles.css"]    # Colores del texto.</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> ES-es</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.85\\linewidth"</span></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/portada_glm.jpg"</span>)</span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>\newpage</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Materiales requeridos para el taller en clase {.titulo-seccion}</span></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>En los siguientes enlaces se podrán descargar archivos comprimidos de los talleres donde se pueden aplicar procedimientos para los modelos de regresión lineal generalizada - GLM, con datos simulados en ecosistemas del Caribe colombiano (📰 Taller 4. Regresión lineal generalizada).</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a>::: material-apoyo</span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="dt">&lt;</span><span class="kw">i</span><span class="ot"> class</span><span class="op">=</span><span class="st">"bi bi-file-earmark-zip"</span><span class="dt">&gt;&lt;/</span><span class="kw">i</span><span class="dt">&gt;</span> <span class="co">[</span><span class="ot">Taller 4. Regresión lineal generalizada</span><span class="co">](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_clase/taller4_clase.zip)</span> </span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a>**Nota:** una vez se descarguen los materiales, se requiere descomprimirlos antes de realizar cualquier procedimiento y seguir las orientaciones del docente para realizar los ejercicios requeridos.</span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a><span class="fu">### Diapositivas en vivo - Slides.com</span></span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a><span class="al">![](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/figuras/slides.com.jpg)</span>{width="110"}</span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a>::: material-apoyo</span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="dt">&lt;</span><span class="kw">i</span><span class="ot"> class</span><span class="op">=</span><span class="st">"bi bi-easel"</span><span class="dt">&gt;&lt;/</span><span class="kw">i</span><span class="dt">&gt;</span> <span class="co">[</span><span class="ot">Diapositivas del Taller 4. GLM</span><span class="co">](https://slides.com/d/rrKfVpI/live)</span> </span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivos del taller</span></span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a>Este taller acompaña la sesión de diapositivas *"Modelos Lineales Generalizados (GLM)"* (RA1, RA2) del sábado en la tarde de la Semana 2. Al terminar, se podrá:</span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Elegir la familia adecuada según el tipo de variable respuesta.</span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Ajustar e interpretar un **GLM binomial** (enlace logit, odds ratio, prueba de razón de verosimilitud).</span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Ajustar e interpretar un **GLM Poisson** (enlace log, razón de tasas).</span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Comparar conteos **entre sitios y épocas**, diagnosticar **sobredispersión** (φ) y corregirla con la **binomial negativa**.</span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a>Se usan los mismos tres ejemplos de las diapositivas, con las mismas semillas, de modo que los resultados coinciden con los que aparecen en ellas.</span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb40-68"><a href="#cb40-68" aria-hidden="true" tabindex="-1"></a><span class="fu">### Núcleo y material complementario</span></span>
<span id="cb40-69"><a href="#cb40-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a>Este taller cubre lo esencial para la sesión. Los temas que amplían el análisis (proporciones, centrado de predictores, intervalos construidos a mano, cuasi-Poisson en detalle, comparaciones por pares, offset y el estudio de caso de la tortuga caguama) están en el <span class="co">[</span><span class="ot">Material complementario</span><span class="co">](#sec-apoyo)</span>, para consultarlos cuando el propio proyecto los requiera.</span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-73"><a href="#cb40-73" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-74"><a href="#cb40-74" aria-hidden="true" tabindex="-1"></a>Los datos siguen siendo **simulados** con <span class="in">`set.seed()`</span> fijando la semilla en cada sección. Construidos para ilustrar cada modelo con claridad, no para representar mediciones reales.</span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE, warning=FALSE}</span></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Librerías requeridas</span></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-81"><a href="#cb40-81" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb40-82"><a href="#cb40-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-83"><a href="#cb40-83" aria-hidden="true" tabindex="-1"></a><span class="co"># La binomial negativa se ajusta con MASS::glm.nb(). Se llama con el prefijo</span></span>
<span id="cb40-84"><a href="#cb40-84" aria-hidden="true" tabindex="-1"></a><span class="co"># MASS:: para no cargar el paquete, que enmascara dplyr::select()</span></span>
<span id="cb40-85"><a href="#cb40-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-86"><a href="#cb40-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-87"><a href="#cb40-87" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-88"><a href="#cb40-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-89"><a href="#cb40-89" aria-hidden="true" tabindex="-1"></a><span class="fu">## Antes de empezar: ¿qué es un GLM? {#sec-fundamentos}</span></span>
<span id="cb40-90"><a href="#cb40-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-91"><a href="#cb40-91" aria-hidden="true" tabindex="-1"></a>Un Modelo Lineal Generalizado tiene tres componentes:</span>
<span id="cb40-92"><a href="#cb40-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-93"><a href="#cb40-93" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Componente aleatorio**: la distribución de la variable respuesta dentro de la familia exponencial. La varianza queda ligada a la media: binomial Var = np(1 − p); Poisson Var = μ.</span>
<span id="cb40-94"><a href="#cb40-94" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Componente sistemático**: el predictor lineal $\eta = \beta_0 + \beta_1X_1 + \dots$, igual que en <span class="in">`lm()`</span>.</span>
<span id="cb40-95"><a href="#cb40-95" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Función de enlace** $g(\mu)$: conecta la media esperada con el predictor lineal, $\eta = g(\mu)$.</span>
<span id="cb40-96"><a href="#cb40-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-97"><a href="#cb40-97" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-98"><a href="#cb40-98" aria-hidden="true" tabindex="-1"></a><span class="fu">### No es lo mismo que transformar Y</span></span>
<span id="cb40-99"><a href="#cb40-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-100"><a href="#cb40-100" aria-hidden="true" tabindex="-1"></a>Transformar <span class="in">`log(Y)`</span> antes de un <span class="in">`lm()`</span> altera cada observación y falla con los ceros (log 0 = −∞), lo que obliga a recursos como <span class="in">`log(Y + 1)`</span>. En un GLM, la función de enlace actúa sobre el **valor esperado** $\mu$ y no sobre los datos: la varianza se modela en su escala real.</span>
<span id="cb40-101"><a href="#cb40-101" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-102"><a href="#cb40-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-103"><a href="#cb40-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tipo de variable respuesta <span class="pp">|</span> Familia <span class="pp">|</span> Enlace <span class="pp">|</span> Ejemplo <span class="pp">|</span></span>
<span id="cb40-104"><a href="#cb40-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------------|-----------------|-----------------|----------------------|</span></span>
<span id="cb40-105"><a href="#cb40-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Continua, aprox. normal <span class="pp">|</span> Gaussiana <span class="pp">|</span> Identidad <span class="pp">|</span> Longitud corporal de un pez <span class="pp">|</span></span>
<span id="cb40-106"><a href="#cb40-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Binaria (0/1) o proporción <span class="pp">|</span> Binomial <span class="pp">|</span> Logit <span class="pp">|</span> Presencia/ausencia, supervivencia <span class="pp">|</span></span>
<span id="cb40-107"><a href="#cb40-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Conteo (0, 1, 2, …) <span class="pp">|</span> Poisson <span class="pp">|</span> Log <span class="pp">|</span> Individuos por cuadrante <span class="pp">|</span></span>
<span id="cb40-108"><a href="#cb40-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Conteo sobredisperso <span class="pp">|</span> Binomial negativa <span class="pp">|</span> Log <span class="pp">|</span> Peces loro por transecto (cardúmenes) <span class="pp">|</span></span>
<span id="cb40-109"><a href="#cb40-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-110"><a href="#cb40-110" aria-hidden="true" tabindex="-1"></a>Las proporciones (p. ej., juveniles vivos de un total por tanque) también se modelan con la familia binomial; la forma de hacerlo está en el material complementario.</span>
<span id="cb40-111"><a href="#cb40-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-112"><a href="#cb40-112" aria-hidden="true" tabindex="-1"></a>Se define desde ya una función para el parámetro de dispersión, que se usará en las Partes 2 y 3:</span>
<span id="cb40-113"><a href="#cb40-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-116"><a href="#cb40-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-117"><a href="#cb40-117" aria-hidden="true" tabindex="-1"></a><span class="co"># φ = suma de residuos de Pearson al cuadrado / g.l. residuales</span></span>
<span id="cb40-118"><a href="#cb40-118" aria-hidden="true" tabindex="-1"></a>phi <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb40-119"><a href="#cb40-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo, <span class="at">type =</span> <span class="st">"pearson"</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> modelo<span class="sc">$</span>df.residual</span>
<span id="cb40-120"><a href="#cb40-120" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb40-121"><a href="#cb40-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-122"><a href="#cb40-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-123"><a href="#cb40-123" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-124"><a href="#cb40-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-125"><a href="#cb40-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parte 1 — GLM binomial: enfermedad de coral y temperatura {#sec-binomial}</span></span>
<span id="cb40-126"><a href="#cb40-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-127"><a href="#cb40-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb40-128"><a href="#cb40-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb40-129"><a href="#cb40-129" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb40-130"><a href="#cb40-130" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb40-131"><a href="#cb40-131" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/1_glm_parte1_binomial.jpg"</span>)</span>
<span id="cb40-132"><a href="#cb40-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-133"><a href="#cb40-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-134"><a href="#cb40-134" aria-hidden="true" tabindex="-1"></a>**Pregunta:** ¿Aumenta con la temperatura la **probabilidad** de que una colonia de coral presente signos de **enfermedad de banda negra**?</span>
<span id="cb40-135"><a href="#cb40-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-138"><a href="#cb40-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-139"><a href="#cb40-139" aria-hidden="true" tabindex="-1"></a><span class="co">#| html-table-processing: none</span></span>
<span id="cb40-140"><a href="#cb40-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-141"><a href="#cb40-141" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb40-142"><a href="#cb40-142" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">365</span>)</span>
<span id="cb40-143"><a href="#cb40-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-144"><a href="#cb40-144" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de colonias</span></span>
<span id="cb40-145"><a href="#cb40-145" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">80</span></span>
<span id="cb40-146"><a href="#cb40-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-147"><a href="#cb40-147" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperatura del agua (°C)</span></span>
<span id="cb40-148"><a href="#cb40-148" aria-hidden="true" tabindex="-1"></a>temperatura <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="dv">27</span>, <span class="fl">31.5</span>), <span class="dv">2</span>)</span>
<span id="cb40-149"><a href="#cb40-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-150"><a href="#cb40-150" aria-hidden="true" tabindex="-1"></a><span class="co"># Presencia (1) o ausencia (0) de la enfermedad</span></span>
<span id="cb40-151"><a href="#cb40-151" aria-hidden="true" tabindex="-1"></a>enfermo <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">14.5</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> temperatura))</span>
<span id="cb40-152"><a href="#cb40-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-153"><a href="#cb40-153" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb40-154"><a href="#cb40-154" aria-hidden="true" tabindex="-1"></a>coral_enf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">colonia =</span> <span class="fu">paste0</span>(<span class="st">"C"</span>, <span class="dv">1</span><span class="sc">:</span>n), temperatura, enfermo)</span>
<span id="cb40-155"><a href="#cb40-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-156"><a href="#cb40-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb40-157"><a href="#cb40-157" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coral_enf, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-158"><a href="#cb40-158" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-159"><a href="#cb40-159" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb40-160"><a href="#cb40-160" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-161"><a href="#cb40-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-162"><a href="#cb40-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-165"><a href="#cb40-165" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-166"><a href="#cb40-166" aria-hidden="true" tabindex="-1"></a><span class="co"># Colonias sanas (0) y enfermas (1)</span></span>
<span id="cb40-167"><a href="#cb40-167" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coral_enf<span class="sc">$</span>enfermo)</span>
<span id="cb40-168"><a href="#cb40-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-169"><a href="#cb40-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-172"><a href="#cb40-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-173"><a href="#cb40-173" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM binomial</span></span>
<span id="cb40-174"><a href="#cb40-174" aria-hidden="true" tabindex="-1"></a>mod_enf <span class="ot">&lt;-</span> <span class="fu">glm</span>(enfermo <span class="sc">~</span> temperatura, <span class="at">data =</span> coral_enf, <span class="at">family =</span> binomial)</span>
<span id="cb40-175"><a href="#cb40-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-176"><a href="#cb40-176" aria-hidden="true" tabindex="-1"></a><span class="co"># Consultar resultados</span></span>
<span id="cb40-177"><a href="#cb40-177" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_enf)</span>
<span id="cb40-178"><a href="#cb40-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-179"><a href="#cb40-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-180"><a href="#cb40-180" aria-hidden="true" tabindex="-1"></a>La columna <span class="in">`z value`</span> es la **prueba de Wald**: z = b₁ / EE. En un GLM se usa z y no t, porque la varianza la fija la familia (binomial o Poisson) en lugar de estimarse aparte.</span>
<span id="cb40-181"><a href="#cb40-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-182"><a href="#cb40-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Prueba de razón de verosimilitud</span></span>
<span id="cb40-183"><a href="#cb40-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-186"><a href="#cb40-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-187"><a href="#cb40-187" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar la devianza con y sin temperatura</span></span>
<span id="cb40-188"><a href="#cb40-188" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_enf, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb40-189"><a href="#cb40-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-190"><a href="#cb40-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-191"><a href="#cb40-191" aria-hidden="true" tabindex="-1"></a>Compara la devianza del modelo nulo con la del modelo con temperatura. Es la prueba preferida para decidir si un predictor aporta, sobre todo con muestras pequeñas.</span>
<span id="cb40-192"><a href="#cb40-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-195"><a href="#cb40-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-196"><a href="#cb40-196" aria-hidden="true" tabindex="-1"></a><span class="co"># Proporción de la devianza explicada (análogo aproximado al r²)</span></span>
<span id="cb40-197"><a href="#cb40-197" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> mod_enf<span class="sc">$</span>deviance <span class="sc">/</span> mod_enf<span class="sc">$</span>null.deviance</span>
<span id="cb40-198"><a href="#cb40-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-199"><a href="#cb40-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-200"><a href="#cb40-200" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb40-201"><a href="#cb40-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Significativo no es lo mismo que explicativo</span></span>
<span id="cb40-202"><a href="#cb40-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-203"><a href="#cb40-203" aria-hidden="true" tabindex="-1"></a>La temperatura reduce la devianza solo un <span class="in">`r round(100 * (1 - mod_enf$deviance / mod_enf$null.deviance), 1)`</span> %. El efecto es real, pero otros factores (especie hospedera, sedimentación, patógenos) explican la mayor parte de la variación.</span>
<span id="cb40-204"><a href="#cb40-204" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-205"><a href="#cb40-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-206"><a href="#cb40-206" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretación: odds ratio</span></span>
<span id="cb40-207"><a href="#cb40-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-210"><a href="#cb40-210" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-211"><a href="#cb40-211" aria-hidden="true" tabindex="-1"></a><span class="co"># OR = exp(b) con su IC 95 %</span></span>
<span id="cb40-212"><a href="#cb40-212" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(mod_enf), <span class="fu">confint</span>(mod_enf)))</span>
<span id="cb40-213"><a href="#cb40-213" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-214"><a href="#cb40-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-215"><a href="#cb40-215" aria-hidden="true" tabindex="-1"></a>Por cada +1 °C, los odds de que la colonia esté enferma se multiplican por <span class="in">`r round(exp(coef(mod_enf)["temperatura"]), 2)`</span> (IC 95 %: <span class="in">`r round(exp(confint(mod_enf))[2, 1], 2)`</span>–<span class="in">`r round(exp(confint(mod_enf))[2, 2], 2)`</span>). Como el IC del OR no incluye 1, la asociación es estadísticamente significativa.</span>
<span id="cb40-216"><a href="#cb40-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-217"><a href="#cb40-217" aria-hidden="true" tabindex="-1"></a>El OR del intercepto es prácticamente 0 porque corresponde a una temperatura de 0 °C, que no tiene sentido biológico. No afecta la interpretación de la temperatura (en el material complementario se muestra cómo volverlo interpretable centrando el predictor).</span>
<span id="cb40-218"><a href="#cb40-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-219"><a href="#cb40-219" aria-hidden="true" tabindex="-1"></a><span class="fu">### Probabilidades predichas</span></span>
<span id="cb40-220"><a href="#cb40-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-223"><a href="#cb40-223" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-224"><a href="#cb40-224" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperaturas de interés</span></span>
<span id="cb40-225"><a href="#cb40-225" aria-hidden="true" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">temperatura =</span> <span class="dv">28</span><span class="sc">:</span><span class="dv">31</span>)</span>
<span id="cb40-226"><a href="#cb40-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-227"><a href="#cb40-227" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidad predicha en la escala de respuesta</span></span>
<span id="cb40-228"><a href="#cb40-228" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(nd, <span class="at">prob =</span> <span class="fu">round</span>(<span class="fu">predict</span>(mod_enf, <span class="at">newdata =</span> nd, <span class="at">type =</span> <span class="st">"response"</span>), <span class="dv">3</span>))</span>
<span id="cb40-229"><a href="#cb40-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-230"><a href="#cb40-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-231"><a href="#cb40-231" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-232"><a href="#cb40-232" aria-hidden="true" tabindex="-1"></a><span class="in">`predict(..., type = "response")`</span> devuelve la probabilidad (0 a 1). Sin <span class="in">`type = "response"`</span> se obtiene el predictor lineal en escala logit.</span>
<span id="cb40-233"><a href="#cb40-233" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-234"><a href="#cb40-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-237"><a href="#cb40-237" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-238"><a href="#cb40-238" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 6</span></span>
<span id="cb40-239"><a href="#cb40-239" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4.2</span></span>
<span id="cb40-240"><a href="#cb40-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-241"><a href="#cb40-241" aria-hidden="true" tabindex="-1"></a><span class="co"># Construir gráfico</span></span>
<span id="cb40-242"><a href="#cb40-242" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coral_enf, <span class="fu">aes</span>(<span class="at">x =</span> temperatura, <span class="at">y =</span> enfermo)) <span class="sc">+</span></span>
<span id="cb40-243"><a href="#cb40-243" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.03</span>, <span class="at">width =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"grey55"</span>) <span class="sc">+</span></span>
<span id="cb40-244"><a href="#cb40-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> binomial),</span>
<span id="cb40-245"><a href="#cb40-245" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"navy"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span>   <span class="co"># Curva logística e IC 95 %</span></span>
<span id="cb40-246"><a href="#cb40-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-247"><a href="#cb40-247" aria-hidden="true" tabindex="-1"></a><span class="co"># Etiquetas de ejes</span></span>
<span id="cb40-248"><a href="#cb40-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Temperatura (°C)"</span>, </span>
<span id="cb40-249"><a href="#cb40-249" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probabilidad de banda negra"</span>) <span class="sc">+</span></span>
<span id="cb40-250"><a href="#cb40-250" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-251"><a href="#cb40-251" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar tema</span></span>
<span id="cb40-252"><a href="#cb40-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-253"><a href="#cb40-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-254"><a href="#cb40-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-255"><a href="#cb40-255" aria-hidden="true" tabindex="-1"></a><span class="in">`geom_smooth()`</span> ajusta el mismo GLM binomial y dibuja la curva con su IC 95 %, que nunca sale de <span class="sc">\[</span>0, 1<span class="sc">\]</span>.</span>
<span id="cb40-256"><a href="#cb40-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-257"><a href="#cb40-257" aria-hidden="true" tabindex="-1"></a>**Para discutir:** el OR es constante (1.65 por °C), pero la probabilidad predicha sube 12 puntos entre 28 y 29 °C y 12 entre 30 y 31 °C, y subiría menos en los extremos de la curva. ¿Por qué un OR constante no implica un aumento constante de la probabilidad?</span>
<span id="cb40-258"><a href="#cb40-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-259"><a href="#cb40-259" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb40-260"><a href="#cb40-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cómo reportar el resultado</span></span>
<span id="cb40-261"><a href="#cb40-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-262"><a href="#cb40-262" aria-hidden="true" tabindex="-1"></a>En la sección de resultados de un artículo o de la tesis, se reportan el efecto en escala interpretable (OR) con su IC, la prueba de razón de verosimilitud y la devianza explicada. Por ejemplo:</span>
<span id="cb40-263"><a href="#cb40-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-264"><a href="#cb40-264" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; La probabilidad de presentar banda negra aumentó con la temperatura del agua (GLM binomial, enlace logit; OR = 1,65 por °C; IC 95 %: 1,18–2,38; χ²~1~ = 8,69; p = 0,003), aunque la temperatura explicó solo el 7,9 % de la devianza.</span></span>
<span id="cb40-265"><a href="#cb40-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-266"><a href="#cb40-266" aria-hidden="true" tabindex="-1"></a>Esta estructura es la que se espera en la Evidencia 2.</span>
<span id="cb40-267"><a href="#cb40-267" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-268"><a href="#cb40-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-269"><a href="#cb40-269" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb40-270"><a href="#cb40-270" aria-hidden="true" tabindex="-1"></a><span class="fu">### Diseño (RA1)</span></span>
<span id="cb40-271"><a href="#cb40-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-272"><a href="#cb40-272" aria-hidden="true" tabindex="-1"></a>Si varias colonias provienen del mismo arrecife y comparten la misma temperatura, no son réplicas independientes para el efecto de la temperatura. En ese caso la unidad de análisis sería el arrecife o se requeriría un modelo mixto (fuera del alcance de esta sesión).</span>
<span id="cb40-273"><a href="#cb40-273" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-274"><a href="#cb40-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-275"><a href="#cb40-275" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-276"><a href="#cb40-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-277"><a href="#cb40-277" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parte 2 — GLM Poisson: langosta espinosa y densidad de pasto {#sec-poisson}</span></span>
<span id="cb40-278"><a href="#cb40-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-279"><a href="#cb40-279" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb40-280"><a href="#cb40-280" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb40-281"><a href="#cb40-281" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb40-282"><a href="#cb40-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb40-283"><a href="#cb40-283" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/2_glm_parte2_poisson.jpg"</span>)</span>
<span id="cb40-284"><a href="#cb40-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-285"><a href="#cb40-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-286"><a href="#cb40-286" aria-hidden="true" tabindex="-1"></a>**Pregunta:** ¿Aumenta el **número de juveniles** de *Panulirus argus* por parche de pastos marinos con la **densidad del pasto**?</span>
<span id="cb40-287"><a href="#cb40-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-290"><a href="#cb40-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-291"><a href="#cb40-291" aria-hidden="true" tabindex="-1"></a><span class="co">#| html-table-processing: none</span></span>
<span id="cb40-292"><a href="#cb40-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-293"><a href="#cb40-293" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb40-294"><a href="#cb40-294" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">28</span>)</span>
<span id="cb40-295"><a href="#cb40-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-296"><a href="#cb40-296" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de parches</span></span>
<span id="cb40-297"><a href="#cb40-297" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">32</span></span>
<span id="cb40-298"><a href="#cb40-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-299"><a href="#cb40-299" aria-hidden="true" tabindex="-1"></a><span class="co"># Índice de densidad de pasto (1–10)</span></span>
<span id="cb40-300"><a href="#cb40-300" aria-hidden="true" tabindex="-1"></a>densidad_pasto <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n2, <span class="dv">1</span>, <span class="dv">10</span>), <span class="dv">1</span>)</span>
<span id="cb40-301"><a href="#cb40-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-302"><a href="#cb40-302" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo de juveniles por parche</span></span>
<span id="cb40-303"><a href="#cb40-303" aria-hidden="true" tabindex="-1"></a>juveniles <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n2, <span class="fu">exp</span>(<span class="fl">0.9</span> <span class="sc">+</span> <span class="fl">0.15</span> <span class="sc">*</span> densidad_pasto))</span>
<span id="cb40-304"><a href="#cb40-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-305"><a href="#cb40-305" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb40-306"><a href="#cb40-306" aria-hidden="true" tabindex="-1"></a>langosta <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">parche =</span> <span class="fu">paste0</span>(<span class="st">"L"</span>, <span class="dv">1</span><span class="sc">:</span>n2), densidad_pasto, juveniles)</span>
<span id="cb40-307"><a href="#cb40-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-308"><a href="#cb40-308" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb40-309"><a href="#cb40-309" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(langosta, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-310"><a href="#cb40-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-311"><a href="#cb40-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb40-312"><a href="#cb40-312" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-313"><a href="#cb40-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-314"><a href="#cb40-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-317"><a href="#cb40-317" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-318"><a href="#cb40-318" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM Poisson</span></span>
<span id="cb40-319"><a href="#cb40-319" aria-hidden="true" tabindex="-1"></a>mod_lang <span class="ot">&lt;-</span> <span class="fu">glm</span>(juveniles <span class="sc">~</span> densidad_pasto, <span class="at">data =</span> langosta, <span class="at">family =</span> poisson)</span>
<span id="cb40-320"><a href="#cb40-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-321"><a href="#cb40-321" aria-hidden="true" tabindex="-1"></a><span class="co"># Consultar resultados</span></span>
<span id="cb40-322"><a href="#cb40-322" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_lang)</span>
<span id="cb40-323"><a href="#cb40-323" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-324"><a href="#cb40-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-325"><a href="#cb40-325" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretación: razón de tasas</span></span>
<span id="cb40-326"><a href="#cb40-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-329"><a href="#cb40-329" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-330"><a href="#cb40-330" aria-hidden="true" tabindex="-1"></a><span class="co"># Razón de tasas del predictor</span></span>
<span id="cb40-331"><a href="#cb40-331" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(mod_lang)[<span class="st">"densidad_pasto"</span>])</span>
<span id="cb40-332"><a href="#cb40-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-333"><a href="#cb40-333" aria-hidden="true" tabindex="-1"></a><span class="co"># IC 95 % en escala exp()</span></span>
<span id="cb40-334"><a href="#cb40-334" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(mod_lang))</span>
<span id="cb40-335"><a href="#cb40-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-336"><a href="#cb40-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-337"><a href="#cb40-337" aria-hidden="true" tabindex="-1"></a>Por cada unidad adicional del índice de densidad de pasto, la abundancia esperada de juveniles se multiplica por <span class="in">`r round(exp(coef(mod_lang)["densidad_pasto"]), 2)`</span>. Esta cantidad, exp(β), es la **razón de tasas** del predictor.</span>
<span id="cb40-338"><a href="#cb40-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-339"><a href="#cb40-339" aria-hidden="true" tabindex="-1"></a><span class="fu">### Verificación de la equidispersión</span></span>
<span id="cb40-340"><a href="#cb40-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-343"><a href="#cb40-343" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-344"><a href="#cb40-344" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb40-345"><a href="#cb40-345" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_lang)</span>
<span id="cb40-346"><a href="#cb40-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-347"><a href="#cb40-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-348"><a href="#cb40-348" aria-hidden="true" tabindex="-1"></a>φ ≈ <span class="in">`r round(phi(mod_lang), 2)`</span>: muy cerca de 1. Este Poisson, sin corrección adicional, es adecuado para estos datos.</span>
<span id="cb40-349"><a href="#cb40-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-350"><a href="#cb40-350" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-351"><a href="#cb40-351" aria-hidden="true" tabindex="-1"></a>Si las unidades de muestreo difieren en área, tiempo o esfuerzo (parches de distinto tamaño, nasas caladas distinto número de horas), el modelo debe incluir un **offset**. Se explica en el material complementario.</span>
<span id="cb40-352"><a href="#cb40-352" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-353"><a href="#cb40-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-354"><a href="#cb40-354" aria-hidden="true" tabindex="-1"></a>**Para discutir:** los juveniles de langosta suelen refugiarse en grupos bajo una misma estructura. Si eso ocurriera en estos parches, ¿qué se esperaría que pasara con φ? ¿Qué consecuencia tendría sobre los valores p del Poisson?</span>
<span id="cb40-355"><a href="#cb40-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-356"><a href="#cb40-356" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-357"><a href="#cb40-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-358"><a href="#cb40-358" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parte 3 — Conteos entre sitios y épocas: sobredispersión {#sec-sobredispersion}</span></span>
<span id="cb40-359"><a href="#cb40-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-360"><a href="#cb40-360" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE, warning=FALSE}</span></span>
<span id="cb40-361"><a href="#cb40-361" aria-hidden="true" tabindex="-1"></a><span class="co">#| out-width: "0.8\\linewidth"</span></span>
<span id="cb40-362"><a href="#cb40-362" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: left</span></span>
<span id="cb40-363"><a href="#cb40-363" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-pos: 'H'</span></span>
<span id="cb40-364"><a href="#cb40-364" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figuras_portadas/3_glm_parte3_sobredispersion.jpg"</span>)</span>
<span id="cb40-365"><a href="#cb40-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-366"><a href="#cb40-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-367"><a href="#cb40-367" aria-hidden="true" tabindex="-1"></a>**Pregunta:** ¿Difiere la **abundancia del pez loro rayado** (*Scarus iseri*) entre zonas con distinto nivel de uso y entre épocas climáticas?</span>
<span id="cb40-368"><a href="#cb40-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-369"><a href="#cb40-369" aria-hidden="true" tabindex="-1"></a>Este es el caso más común en monitoreos ecológicos: un **conteo** y uno o dos **factores** (sitio, zona, época). Es el equivalente de un ANOVA de dos vías, pero para conteos. En cada zona (uso intensivo, intermedia y protegida) y en cada época (seca y lluviosa) se censaron 8 transectos ubicados al azar: 48 transectos en total.</span>
<span id="cb40-370"><a href="#cb40-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-373"><a href="#cb40-373" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-374"><a href="#cb40-374" aria-hidden="true" tabindex="-1"></a><span class="co">#| html-table-processing: none</span></span>
<span id="cb40-375"><a href="#cb40-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-376"><a href="#cb40-376" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproducibilidad</span></span>
<span id="cb40-377"><a href="#cb40-377" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">147</span>)</span>
<span id="cb40-378"><a href="#cb40-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-379"><a href="#cb40-379" aria-hidden="true" tabindex="-1"></a><span class="co"># Zona de uso (3 niveles; "Uso intensivo" es el nivel de referencia)</span></span>
<span id="cb40-380"><a href="#cb40-380" aria-hidden="true" tabindex="-1"></a>zona <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Uso intensivo"</span>, <span class="st">"Intermedia"</span>, <span class="st">"Protegida"</span>), <span class="at">each =</span> <span class="dv">16</span>),</span>
<span id="cb40-381"><a href="#cb40-381" aria-hidden="true" tabindex="-1"></a>               <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Uso intensivo"</span>, <span class="st">"Intermedia"</span>, <span class="st">"Protegida"</span>))</span>
<span id="cb40-382"><a href="#cb40-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-383"><a href="#cb40-383" aria-hidden="true" tabindex="-1"></a><span class="co"># Época climática (2 niveles; "Seca" es el nivel de referencia)</span></span>
<span id="cb40-384"><a href="#cb40-384" aria-hidden="true" tabindex="-1"></a>epoca <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Seca"</span>, <span class="st">"Lluviosa"</span>), <span class="at">each =</span> <span class="dv">8</span>), <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb40-385"><a href="#cb40-385" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Seca"</span>, <span class="st">"Lluviosa"</span>))</span>
<span id="cb40-386"><a href="#cb40-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-387"><a href="#cb40-387" aria-hidden="true" tabindex="-1"></a><span class="co"># Abundancia esperada por zona y época</span></span>
<span id="cb40-388"><a href="#cb40-388" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">1.3</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.45</span>, <span class="fl">0.95</span>)[<span class="fu">as.integer</span>(zona)] <span class="sc">-</span> <span class="fl">0.35</span> <span class="sc">*</span> (epoca <span class="sc">==</span> <span class="st">"Lluviosa"</span>))</span>
<span id="cb40-389"><a href="#cb40-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-390"><a href="#cb40-390" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteos agregados (binomial negativa)</span></span>
<span id="cb40-391"><a href="#cb40-391" aria-hidden="true" tabindex="-1"></a>abundancia <span class="ot">&lt;-</span> <span class="fu">rnbinom</span>(<span class="dv">48</span>, <span class="at">mu =</span> mu, <span class="at">size =</span> <span class="fl">2.5</span>)</span>
<span id="cb40-392"><a href="#cb40-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-393"><a href="#cb40-393" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear base de datos</span></span>
<span id="cb40-394"><a href="#cb40-394" aria-hidden="true" tabindex="-1"></a>loro <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">transecto =</span> <span class="fu">paste0</span>(<span class="st">"T"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">48</span>), zona, epoca, abundancia)</span>
<span id="cb40-395"><a href="#cb40-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-396"><a href="#cb40-396" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla con los datos</span></span>
<span id="cb40-397"><a href="#cb40-397" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(loro, <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-398"><a href="#cb40-398" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-399"><a href="#cb40-399" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb40-400"><a href="#cb40-400" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-401"><a href="#cb40-401" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-402"><a href="#cb40-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-403"><a href="#cb40-403" aria-hidden="true" tabindex="-1"></a><span class="fu">### Paso 1 — Explorar: media y varianza por grupo</span></span>
<span id="cb40-404"><a href="#cb40-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-407"><a href="#cb40-407" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-408"><a href="#cb40-408" aria-hidden="true" tabindex="-1"></a><span class="co">#| html-table-processing: none</span></span>
<span id="cb40-409"><a href="#cb40-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-410"><a href="#cb40-410" aria-hidden="true" tabindex="-1"></a><span class="co"># Media y varianza de la abundancia en cada combinación de zona y época</span></span>
<span id="cb40-411"><a href="#cb40-411" aria-hidden="true" tabindex="-1"></a>loro <span class="sc">%&gt;%</span></span>
<span id="cb40-412"><a href="#cb40-412" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(zona, epoca) <span class="sc">%&gt;%</span></span>
<span id="cb40-413"><a href="#cb40-413" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(abundancia), <span class="dv">1</span>),</span>
<span id="cb40-414"><a href="#cb40-414" aria-hidden="true" tabindex="-1"></a>            <span class="at">varianza =</span> <span class="fu">round</span>(<span class="fu">var</span>(abundancia), <span class="dv">1</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-415"><a href="#cb40-415" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-416"><a href="#cb40-416" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb40-417"><a href="#cb40-417" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-418"><a href="#cb40-418" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-419"><a href="#cb40-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-422"><a href="#cb40-422" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-423"><a href="#cb40-423" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 6</span></span>
<span id="cb40-424"><a href="#cb40-424" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb40-425"><a href="#cb40-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-426"><a href="#cb40-426" aria-hidden="true" tabindex="-1"></a><span class="co"># Abundancia por zona y época</span></span>
<span id="cb40-427"><a href="#cb40-427" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loro, <span class="fu">aes</span>(<span class="at">x =</span> zona, <span class="at">y =</span> abundancia, <span class="at">fill =</span> epoca)) <span class="sc">+</span></span>
<span id="cb40-428"><a href="#cb40-428" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb40-429"><a href="#cb40-429" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Zona"</span>, <span class="at">y =</span> <span class="st">"Peces loro por transecto"</span>, <span class="at">fill =</span> <span class="st">"Época"</span>) <span class="sc">+</span></span>
<span id="cb40-430"><a href="#cb40-430" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb40-431"><a href="#cb40-431" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-432"><a href="#cb40-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-433"><a href="#cb40-433" aria-hidden="true" tabindex="-1"></a>En un Poisson, la varianza debería parecerse a la media. Aquí, en varios grupos, la varianza es bastante mayor que la media: es la primera señal de **sobredispersión**, típica de peces que se mueven en grupos.</span>
<span id="cb40-434"><a href="#cb40-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-435"><a href="#cb40-435" aria-hidden="true" tabindex="-1"></a><span class="fu">### Paso 2 — Ajustar el Poisson e inspeccionar φ</span></span>
<span id="cb40-436"><a href="#cb40-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-439"><a href="#cb40-439" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-440"><a href="#cb40-440" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar GLM Poisson con zona, época y su interacción</span></span>
<span id="cb40-441"><a href="#cb40-441" aria-hidden="true" tabindex="-1"></a>mod_loro_p <span class="ot">&lt;-</span> <span class="fu">glm</span>(abundancia <span class="sc">~</span> zona <span class="sc">*</span> epoca, <span class="at">data =</span> loro, <span class="at">family =</span> poisson)</span>
<span id="cb40-442"><a href="#cb40-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-443"><a href="#cb40-443" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb40-444"><a href="#cb40-444" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_loro_p)</span>
<span id="cb40-445"><a href="#cb40-445" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-446"><a href="#cb40-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-447"><a href="#cb40-447" aria-hidden="true" tabindex="-1"></a>φ ≈ <span class="in">`r round(phi(mod_loro_p), 2)`</span>, claramente mayor que 1: hay **sobredispersión**. Si se reportara este Poisson, los errores estándar quedarían subestimados y los valores p exagerarían la evidencia.</span>
<span id="cb40-448"><a href="#cb40-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-449"><a href="#cb40-449" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-450"><a href="#cb40-450" aria-hidden="true" tabindex="-1"></a><span class="fu">### ¿Desde qué valor de φ hay que preocuparse?</span></span>
<span id="cb40-451"><a href="#cb40-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-452"><a href="#cb40-452" aria-hidden="true" tabindex="-1"></a>No hay un corte único. Valores cercanos a 1 son compatibles con el Poisson; muchos autores usan 1,2–1,5 como **regla práctica** para empezar a revisar, y valores como 2 o más indican una sobredispersión que no conviene ignorar. Más que el umbral, importa si la corrección cambia las conclusiones.</span>
<span id="cb40-453"><a href="#cb40-453" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-454"><a href="#cb40-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-455"><a href="#cb40-455" aria-hidden="true" tabindex="-1"></a><span class="fu">### Paso 3 — Corregir con la binomial negativa</span></span>
<span id="cb40-456"><a href="#cb40-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-457"><a href="#cb40-457" aria-hidden="true" tabindex="-1"></a>La binomial negativa supone Var = μ + μ²/θ: añade un parámetro θ que absorbe la agregación (a menor θ, mayor agregación). Se ajusta con <span class="in">`MASS::glm.nb()`</span> y la misma fórmula:</span>
<span id="cb40-458"><a href="#cb40-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-461"><a href="#cb40-461" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-462"><a href="#cb40-462" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar binomial negativa</span></span>
<span id="cb40-463"><a href="#cb40-463" aria-hidden="true" tabindex="-1"></a>mod_loro_nb <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(abundancia <span class="sc">~</span> zona <span class="sc">*</span> epoca, <span class="at">data =</span> loro)</span>
<span id="cb40-464"><a href="#cb40-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-465"><a href="#cb40-465" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetro de dispersión</span></span>
<span id="cb40-466"><a href="#cb40-466" aria-hidden="true" tabindex="-1"></a><span class="fu">phi</span>(mod_loro_nb)</span>
<span id="cb40-467"><a href="#cb40-467" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-468"><a href="#cb40-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-471"><a href="#cb40-471" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-472"><a href="#cb40-472" aria-hidden="true" tabindex="-1"></a><span class="co">#| html-table-processing: none</span></span>
<span id="cb40-473"><a href="#cb40-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-474"><a href="#cb40-474" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparar los dos modelos</span></span>
<span id="cb40-475"><a href="#cb40-475" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb40-476"><a href="#cb40-476" aria-hidden="true" tabindex="-1"></a>  <span class="at">modelo =</span> <span class="fu">c</span>(<span class="st">"Poisson"</span>, <span class="st">"Binomial negativa"</span>),</span>
<span id="cb40-477"><a href="#cb40-477" aria-hidden="true" tabindex="-1"></a>  <span class="at">phi =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">phi</span>(mod_loro_p), <span class="fu">phi</span>(mod_loro_nb)), <span class="dv">2</span>),</span>
<span id="cb40-478"><a href="#cb40-478" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(mod_loro_p), <span class="fu">AIC</span>(mod_loro_nb)), <span class="dv">1</span>)</span>
<span id="cb40-479"><a href="#cb40-479" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb40-480"><a href="#cb40-480" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">longtable =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-481"><a href="#cb40-481" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb40-482"><a href="#cb40-482" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">row_spec</span>(<span class="dv">0</span>, <span class="at">bold =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-483"><a href="#cb40-483" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-484"><a href="#cb40-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-485"><a href="#cb40-485" aria-hidden="true" tabindex="-1"></a>Con la binomial negativa, φ queda cerca de 1 y el AIC baja de <span class="in">`r round(AIC(mod_loro_p), 1)`</span> a <span class="in">`r round(AIC(mod_loro_nb), 1)`</span>: es el modelo adecuado para estos datos. Otra alternativa es el **cuasi-Poisson** (<span class="in">`family = quasipoisson`</span>), que corrige los errores estándar pero no permite calcular AIC; se compara con la binomial negativa en el material complementario.</span>
<span id="cb40-486"><a href="#cb40-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-487"><a href="#cb40-487" aria-hidden="true" tabindex="-1"></a><span class="fu">### Paso 4 — ¿Hay diferencias entre zonas y épocas?</span></span>
<span id="cb40-488"><a href="#cb40-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-489"><a href="#cb40-489" aria-hidden="true" tabindex="-1"></a>Como en un ANOVA, primero se revisa la interacción con la **prueba de razón de verosimilitud**:</span>
<span id="cb40-490"><a href="#cb40-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-493"><a href="#cb40-493" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-494"><a href="#cb40-494" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de razón de verosimilitud para cada término</span></span>
<span id="cb40-495"><a href="#cb40-495" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_loro_nb, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb40-496"><a href="#cb40-496" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-497"><a href="#cb40-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-498"><a href="#cb40-498" aria-hidden="true" tabindex="-1"></a>La interacción no es significativa (p = <span class="in">`r round(anova(mod_loro_nb, test = "Chisq")[4, "Pr(&gt;Chi)"], 2)`</span>): la diferencia entre zonas es similar en las dos épocas. Se ajusta entonces el modelo aditivo, más sencillo, y se prueba cada factor:</span>
<span id="cb40-499"><a href="#cb40-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-502"><a href="#cb40-502" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-503"><a href="#cb40-503" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo aditivo: zona + época</span></span>
<span id="cb40-504"><a href="#cb40-504" aria-hidden="true" tabindex="-1"></a>mod_loro <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(abundancia <span class="sc">~</span> zona <span class="sc">+</span> epoca, <span class="at">data =</span> loro)</span>
<span id="cb40-505"><a href="#cb40-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-506"><a href="#cb40-506" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de razón de verosimilitud para cada factor</span></span>
<span id="cb40-507"><a href="#cb40-507" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_loro, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb40-508"><a href="#cb40-508" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-509"><a href="#cb40-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-510"><a href="#cb40-510" aria-hidden="true" tabindex="-1"></a>Se usa esta prueba, y no los valores p de <span class="in">`summary()`</span>, porque la zona tiene tres niveles: la prueba evalúa el factor completo (χ² con 2 g.l.), mientras que cada coeficiente de <span class="in">`summary()`</span> solo compara una zona con la de referencia.</span>
<span id="cb40-511"><a href="#cb40-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-512"><a href="#cb40-512" aria-hidden="true" tabindex="-1"></a><span class="fu">### Paso 5 — Interpretar: razones de tasas</span></span>
<span id="cb40-513"><a href="#cb40-513" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-516"><a href="#cb40-516" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-517"><a href="#cb40-517" aria-hidden="true" tabindex="-1"></a><span class="co"># Razones de tasas e IC 95 %</span></span>
<span id="cb40-518"><a href="#cb40-518" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">RT =</span> <span class="fu">coef</span>(mod_loro), <span class="fu">confint</span>(mod_loro)))</span>
<span id="cb40-519"><a href="#cb40-519" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-520"><a href="#cb40-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-521"><a href="#cb40-521" aria-hidden="true" tabindex="-1"></a>Con factores, cada razón de tasas compara un nivel con el **nivel de referencia** (uso intensivo para la zona, época seca para la época):</span>
<span id="cb40-522"><a href="#cb40-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-523"><a href="#cb40-523" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>En la zona **protegida**, la abundancia esperada es <span class="in">`r round(exp(coef(mod_loro)["zonaProtegida"]), 2)`</span> veces la de la zona de uso intensivo (IC 95 %: <span class="in">`r round(exp(confint(mod_loro))["zonaProtegida", 1], 2)`</span>–<span class="in">`r round(exp(confint(mod_loro))["zonaProtegida", 2], 2)`</span>).</span>
<span id="cb40-524"><a href="#cb40-524" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La zona **intermedia** no difiere con claridad de la de uso intensivo: su IC (<span class="in">`r round(exp(confint(mod_loro))["zonaIntermedia", 1], 2)`</span>–<span class="in">`r round(exp(confint(mod_loro))["zonaIntermedia", 2], 2)`</span>) incluye 1.</span>
<span id="cb40-525"><a href="#cb40-525" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>En la época **lluviosa**, la abundancia esperada es <span class="in">`r round(exp(coef(mod_loro)["epocaLluviosa"]), 2)`</span> veces la de la época seca, es decir, un <span class="in">`r round(100 * (1 - exp(coef(mod_loro)["epocaLluviosa"])))`</span> % menor.</span>
<span id="cb40-526"><a href="#cb40-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-527"><a href="#cb40-527" aria-hidden="true" tabindex="-1"></a>La comparación entre la zona intermedia y la protegida no aparece en esta tabla; las **comparaciones por pares** entre todas las zonas están en el material complementario.</span>
<span id="cb40-528"><a href="#cb40-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-529"><a href="#cb40-529" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb40-530"><a href="#cb40-530" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cómo reportar el resultado</span></span>
<span id="cb40-531"><a href="#cb40-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-532"><a href="#cb40-532" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; La abundancia de *S. iseri* difirió entre zonas (GLM binomial negativa, enlace log; χ²~2~ = 18,7; p </span><span class="sc">\&lt;</span><span class="at"> 0,001) y entre épocas (χ²~1~ = 4,3; p = 0,038), sin interacción entre ambos factores. En la zona protegida, la abundancia esperada fue 3,1 veces la de la zona de uso intensivo (IC 95 %: 1,8–5,3). Se descartó el modelo Poisson por sobredispersión (φ = 3,4; ΔAIC = 42,3).</span></span>
<span id="cb40-533"><a href="#cb40-533" aria-hidden="true" tabindex="-1"></a><span class="at">:::</span></span>
<span id="cb40-534"><a href="#cb40-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-535"><a href="#cb40-535" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-536"><a href="#cb40-536" aria-hidden="true" tabindex="-1"></a><span class="fu">### Del GLM a PERMANOVA (Semana 4)</span></span>
<span id="cb40-537"><a href="#cb40-537" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-538"><a href="#cb40-538" aria-hidden="true" tabindex="-1"></a>Este GLM responde la pregunta **especie por especie**: ¿cambia la abundancia del pez loro entre zonas y épocas? Si la pregunta es si cambia la **comunidad completa** (todas las especies a la vez), se necesita un análisis multivariado como PERMANOVA o ANOSIM, que se trabaja en la Semana 4. En un estudio de diversidad, ambos enfoques se complementan: el multivariado muestra si la comunidad difiere y el GLM muestra qué especies explican esa diferencia.</span>
<span id="cb40-539"><a href="#cb40-539" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-540"><a href="#cb40-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-541"><a href="#cb40-541" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-542"><a href="#cb40-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-543"><a href="#cb40-543" aria-hidden="true" tabindex="-1"></a><span class="fu">## Parte 4 — Lista de verificación antes de reportar el GLM {#sec-checklist}</span></span>
<span id="cb40-544"><a href="#cb40-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-545"><a href="#cb40-545" aria-hidden="true" tabindex="-1"></a>Antes de reportar cualquier GLM, conviene verificar:</span>
<span id="cb40-546"><a href="#cb40-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-547"><a href="#cb40-547" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>¿Se eligió la familia según el tipo real de la variable respuesta?</span>
<span id="cb40-548"><a href="#cb40-548" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>¿Se reportaron los efectos en escala interpretable (OR o razón de tasas) con su IC 95 %?</span>
<span id="cb40-549"><a href="#cb40-549" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>¿Se evaluó el efecto con la prueba de razón de verosimilitud (<span class="in">`anova(..., test = "Chisq")`</span>), sobre todo si el predictor es un factor con más de dos niveles?</span>
<span id="cb40-550"><a href="#cb40-550" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>En los modelos de conteo, ¿se calculó φ? Si es claramente mayor que 1, ¿se corrigió con binomial negativa (o cuasi-Poisson)?</span>
<span id="cb40-551"><a href="#cb40-551" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si las unidades de muestreo difieren en área, tiempo o esfuerzo, ¿se incluyó un offset? (ver material complementario)</span>
<span id="cb40-552"><a href="#cb40-552" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>¿Se evitó extrapolar fuera del rango observado de los predictores?</span>
<span id="cb40-553"><a href="#cb40-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-554"><a href="#cb40-554" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-555"><a href="#cb40-555" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-556"><a href="#cb40-556" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cierre — Una base para el futuro proyecto de grado</span></span>
<span id="cb40-557"><a href="#cb40-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-558"><a href="#cb40-558" aria-hidden="true" tabindex="-1"></a><span class="fu">### Actividad en clase (10 minutos, sin código)</span></span>
<span id="cb40-559"><a href="#cb40-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-560"><a href="#cb40-560" aria-hidden="true" tabindex="-1"></a>En parejas, se responde sobre el proyecto de grado de cada integrante:</span>
<span id="cb40-561"><a href="#cb40-561" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-562"><a href="#cb40-562" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>¿La variable de interés es presencia/ausencia, una proporción o un conteo?</span>
<span id="cb40-563"><a href="#cb40-563" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Según eso, ¿qué familia y qué función de enlace corresponden?</span>
<span id="cb40-564"><a href="#cb40-564" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>¿Qué predictores se incluirían (continuos como temperatura o profundidad, o factores como sitio y época), y con qué justificación?</span>
<span id="cb40-565"><a href="#cb40-565" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Si es un conteo, ¿se esperaría sobredispersión (agregación, parches, exceso de ceros)?</span>
<span id="cb40-566"><a href="#cb40-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-567"><a href="#cb40-567" aria-hidden="true" tabindex="-1"></a>Luego, se escribe la ecuación del GLM en palabras: "la probabilidad / el conteo de <span class="sc">\_\_\_</span> depende de <span class="sc">\_\_\_</span>, y se espera que <span class="sc">\[</span>aumente/disminuya<span class="sc">\]</span> porque <span class="sc">\_\_\_</span>".</span>
<span id="cb40-568"><a href="#cb40-568" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-569"><a href="#cb40-569" aria-hidden="true" tabindex="-1"></a><span class="fu">### Antes de la próxima sesión (tarea corta)</span></span>
<span id="cb40-570"><a href="#cb40-570" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-571"><a href="#cb40-571" aria-hidden="true" tabindex="-1"></a>Se puede adaptar el código de este taller a la propia idea, con **valores simulados pero plausibles** para el sistema de estudio:</span>
<span id="cb40-572"><a href="#cb40-572" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-573"><a href="#cb40-573" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Se copia la sección más parecida a la variable propia (binaria → <span class="co">[</span><span class="ot">Parte 1</span><span class="co">](#sec-binomial)</span>; conteo con un predictor continuo → <span class="co">[</span><span class="ot">Parte 2</span><span class="co">](#sec-poisson)</span>; conteo entre sitios o épocas → <span class="co">[</span><span class="ot">Parte 3</span><span class="co">](#sec-sobredispersion)</span>).</span>
<span id="cb40-574"><a href="#cb40-574" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Se cambian los nombres de las variables y los coeficientes simulados por los esperados en el propio tema.</span>
<span id="cb40-575"><a href="#cb40-575" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Se ejecutan <span class="in">`anova(..., test = "Chisq")`</span> y <span class="in">`phi()`</span> sobre el modelo, y se revisa la lista de verificación (<span class="co">[</span><span class="ot">Parte 4</span><span class="co">](#sec-checklist)</span>). ¿La salida de R es coherente con lo planteado?</span>
<span id="cb40-576"><a href="#cb40-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-577"><a href="#cb40-577" aria-hidden="true" tabindex="-1"></a>Con esto se cierran las Evidencias 1 y 2 (inferencia, regresión y GLM) y se completa el flujo: elegir familia → ajustar → interpretar en escala exp() → diagnosticar → comparar modelos.</span>
<span id="cb40-578"><a href="#cb40-578" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-579"><a href="#cb40-579" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-580"><a href="#cb40-580" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-581"><a href="#cb40-581" aria-hidden="true" tabindex="-1"></a><span class="fu">## Material de apoyo {#sec-apoyo}</span></span>
<span id="cb40-582"><a href="#cb40-582" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-583"><a href="#cb40-583" aria-hidden="true" tabindex="-1"></a><span class="al">![](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/html/figuras_portadas/3_hipotesis/9_material_apoyo.jpg)</span>{width="146"}</span>
<span id="cb40-584"><a href="#cb40-584" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-585"><a href="#cb40-585" aria-hidden="true" tabindex="-1"></a>Para repasar y profundizar después de la sesión:</span>
<span id="cb40-586"><a href="#cb40-586" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-587"><a href="#cb40-587" aria-hidden="true" tabindex="-1"></a>::: material-apoyo</span>
<span id="cb40-588"><a href="#cb40-588" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="dt">&lt;</span><span class="kw">i</span><span class="ot"> class</span><span class="op">=</span><span class="st">"bi bi-ui-checks"</span><span class="dt">&gt;&lt;/</span><span class="kw">i</span><span class="dt">&gt;</span> <span class="co">[</span><span class="ot">**Cuestionario 1 · GLM binomial y Poisson**</span><span class="co">](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Cuestionario1_GLM.html)</span> — 12 preguntas de opción múltiple con pista y explicación, basadas en las Partes 1 a 4 de este taller.</span>
<span id="cb40-589"><a href="#cb40-589" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="dt">&lt;</span><span class="kw">i</span><span class="ot"> class</span><span class="op">=</span><span class="st">"bi bi-ui-checks"</span><span class="dt">&gt;&lt;/</span><span class="kw">i</span><span class="dt">&gt;</span>  <span class="co">[</span><span class="ot">**Cuestionario 2 · GLM binomial y Poisson**</span><span class="co">](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Cuestionario2_GLM.html)</span> — escenarios nuevos con preguntas abiertas para interpretar salidas de modelos, con retroalimentación al final.</span>
<span id="cb40-590"><a href="#cb40-590" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="dt">&lt;</span><span class="kw">i</span><span class="ot"> class</span><span class="op">=</span><span class="st">"bi bi-journal-text"</span><span class="dt">&gt;&lt;/</span><span class="kw">i</span><span class="dt">&gt;</span> <span class="co">[</span><span class="ot">**Material complementario · Cuando el GLM se complica**</span><span class="co">](https://javier-2712.github.io/Manuales/8.Manual_diseno_msc/talleres_complemento/taller4/Complemento_Taller4.html)</span> — proporciones, centrado de predictores, intervalos en escala logit, sobredispersión a fondo (cuasi-Poisson y binomial negativa), comparaciones por pares entre sitios, offset y el estudio de caso de nidos de tortuga caguama.</span>
<span id="cb40-591"><a href="#cb40-591" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb40-592"><a href="#cb40-592" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-593"><a href="#cb40-593" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb40-594"><a href="#cb40-594" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-595"><a href="#cb40-595" aria-hidden="true" tabindex="-1"></a><span class="fu">## Referencias</span></span>
<span id="cb40-596"><a href="#cb40-596" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-597"><a href="#cb40-597" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Quinn, G. P., &amp; Keough, M. J. (2024). *Experimental Design and Data Analysis for Biologists* (2nd ed.). Cambridge University Press. <span class="co">[</span><span class="ot">enlace_ejercicios</span><span class="co">](https://mjkeough.github.io/examples.html)</span></span>
<span id="cb40-598"><a href="#cb40-598" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-599"><a href="#cb40-599" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Logan, M. (2011). *Biostatistical Design and Analysis Using R*. Wiley-Blackwell. <span class="co">[</span><span class="ot">enlace_ejercicios</span><span class="co">](https://bcs.wiley.com/he-bcs/Books?action=index&amp;bcsId=5684&amp;itemId=1405190086)</span>; <span class="co">[</span><span class="ot">enlace_libro</span><span class="co">](https://onlinelibrary.wiley.com/doi/book/10.1002/9781444319620)</span></span>
<span id="cb40-600"><a href="#cb40-600" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-601"><a href="#cb40-601" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Calvo Sendín, J. F. (2025). *Análisis estadístico de datos biológicos en R*. Universidad de Murcia. — Referencia técnica para GLM binomial/Poisson y sobredispersión. <span class="co">[</span><span class="ot">enlace</span><span class="co">](https://webs.um.es/jfcalvo/aedbr.html?utm_source=acortador&amp;utm_medium=referral&amp;utm_campaign=acortador_url&amp;utm_id=aedbr)</span></span>
<span id="cb40-602"><a href="#cb40-602" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-603"><a href="#cb40-603" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb40-604"><a href="#cb40-604" aria-hidden="true" tabindex="-1"></a>Los ejemplos y bases de datos de este taller son de elaboración propia para este curso; no reproducen los ejercicios ni el código de las fuentes citadas.</span>
<span id="cb40-605"><a href="#cb40-605" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>