# Resumen {.unnumbered}

<b style='color:#1f78b4;'>

Repositorio de Talleres de Ecología 1 - 2024-I

</b>

<b style='color:#1f78b4;'>

Javier Rodríguez-Barrios

</b>

<b style='color:#1f78b4;'>

Programa de Biología

</b>

<b style='color:#1f78b4;'> 

"Actualizado: `r Sys.Date()`"

</b>

<div style="text-align: justify">

El siguiente documento es un compendio de temas vistos en el componente teórico y práctico de la asignatura de Ecología 1, durante el periodo 2023-II. Se fundamenta en tres grandes módulos:

-   **Ambiente en ecosistemas**.

-   **Ecología de Poblaciones**.

-   **Ecología de comunidades (parte 1)**.

<div style="text-align: justify">

A partir de ello, el enfoque de este trabajo, consiste en ofrecer a los estudiantes una compilación de los materiales entregados durante la asignatura, como videos de las clases y talleres de cómputo, por lo que este documento se constituye en un repositorio de materiales vistos en clase.

Para un mejor entendimiento de este documento, se sugiere complementar la información con las referencias bibliográficas sugeridas en cada capitulo descrito a continuación.
